### ISSUE TITLE
Runtime png image files were damaged by previous commit

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1007]
The current PNG files in the gldcore/rt folder are invalid, probably damaged by a previous commit with incorrect file properties settings.  The correct ones can be obtained from github.com/dchassin/gridlabd/tree/master/gldcore/rt.

**Comment by afisher1** [comment]
Thanks Dave I'll make sure those are added to the ignore line endings file.

**Comment by afisher1** [comment]
fixed
