### ISSUE TITLE
Add json encoding and decoding to the fncs_msg object

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1010]
GridAPPS-D requires GridLAB-D to be able to encode and decode json structured messages to recieve data from other GridAPPS-D applications and to send data to other GridAPPS-D applications. I propose adding this capability to the fncs_msg object as FNCS is how GridLAB-D is communicating with the GOSS message bus.

**Comment by huangrenke** [comment]
developed and tested the json decoding and encoding, publishing and subscribing in gridlabd: fncs_msg.cpp and fncs_msg.h.
