### ISSUE TITLE
Some err_ validate files failing on windows 10 build

### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#1014]
From observation, some of the err_ validate files fail on windows 10 builds. They seem to pass in other versions of windows (such as 7, 8 etc.)

**Comment by ftuffner** [comment]
This looks to be a duplicate of the existing issue #965, especially since it is only the "_err" autotests again.

**Comment by nikhilgupta10** [comment]
True. Closing this ticket.
