### ISSUE TITLE
GridLAB-D Windows built .dlls, .exe not working without third-party and win-builds .dlls

### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#1015]
Once the GridLAB-D is built, typically (pre-Mingw), the .dlls and .exe can be copied to a different computer to run the .exe (after setting appropriate $PATH). GridLAB-D built with MinGW is asking for win-builds .dlls and dlfcn .dll to work. Track the requirements and fix:

1. Identify how many of these dependency .dlls are required? (This might be tested by copying one after the other until the error is gone and .exe runs)
2. How to eliminate this dependency to simply run .exe using GridLAB-D .dlls?

**Comment by nikhilgupta10** [comment]
More information on the error:

Test-1: I removed all MinGW related from my $PATH, ran gridlabd from cmd. ERRORS about missing .dlls:
1. libdl.dll
2. libstdc++-6.dll
3. libgcc_s_seh-1.dll
4. libwinpthread-1.dll

Test-2: Now, added the following to $PATH (These directories depend upon where your MinGW is installed on the computer. In my case, all my MinGW stuff is in my C:/...)
C:\MinGW\bin
C:\MinGW\msys\1.0\opt\windows_64\bin
C:\MinGW\msys\1.0\opt\windows_64\mingw\bin

NOTE: Make sure your <GridLABD$PATH>/lib/gridlabd; <GridLABD$PATH>/share/gridlabd is in your GLPATH; where <GridLABD$PATH> is the "install" directory (where GridLAB-D is directed to install during build process)

Continuing to play with the MinGW directory additions/deletions, etc. Watch the comments for progress/updates.

**Comment by nikhilgupta10** [comment]
Test-3: Copied those .dlls to a "test" folder; deleted MinGW related from the $PATH. Added the newly created "test" folder to the $PATH. 

rESULT: GRIDLABD --VERSION WORKS FINE

Works fine with just pointing to those four .dlls (which is better than a whole bunch of other dependencies)

**Comment by nikhilgupta10** [comment]
@ntenney Can you please add those above 4 .dlls to the PATHs I detailed in above comments through "GLD installer"?
(Once we get a green signal from @jcfuller1 to do so regarding licenses etc,)

**Comment by nikhilgupta10** [comment]
After a lot of digging around, I found information about the licensing of the .dlls. As you know we, now, need to distribute 4 .dlls along with GridLAB-D .dlls to work on a fresh machine:
1.	libdl.dll
2.	libstdc++-6.dll
3.	libgcc_s_seh-1.dll
4.	libwinpthread-1.dll

Regarding the licensing, the very first one (libdl.dll) is part of “dlfcn” and its license can be found here: https://github.com/dlfcn-win32/dlfcn-win32

Where as the remaining .dlls go, it got little tricky to find the licenses. Some important points regarding that:
•	Win-builds home page states that it is a “LARGE DISTRIBUTION OF BINARY PACKAGES FOR WINDOWS” (http://win-builds.org/doku.php) and these packages are listed in: http://win-builds.org/doku.php/1.5.0_packages
o	libstdc	++-6.dll: This belongs to “gcc-g++ 4.8.3-2 - C++ for GCC” package. Falls under GPL: https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.license.what
o	libgcc_s_seh-1.dll: This belongs to “gcc 4.8.3-2 - Base GCC package with C support” package. Falls under GPL: https://gcc.gnu.org/onlinedocs/gcc-4.8.3/gcc/index.html#toc_Copying 
o	libwinpthread-1.dll: This belongs to “winpthreads v3.3.0-2 - No description” package. Attached the COPYING with this email that has “copyrights information”. (Can be distributed with the conditions in the COPYING attachment)

More information/posts:
https://sourceforge.net/p/mingw-w64/mailman/message/27187659/ talks about libstdc++ license. In the link, grep for “license”
https://sourceforge.net/p/mingw-w64/mailman/message/28301141/ talks about libwinpthreads license. In think link, grep for the dll name or “license”

These are slightly related but we might not need to take a look at them:

http://stackoverflow.com/questions/31449769/distribute-program-compiled-with-mingw-g talks about distributing those .dlls (except the dlfcn .dll)
https://www.neowin.net/forum/topic/1194367-is-libwinpthread-1dll-covered-by-the-gcc-runtime-library-exception/ talks about libwinpthreads distribution.

**Comment by afisher1** [comment]
@jcfuller1 can I close this ticket? Now that we got the ok from legal. Or is what we got from legal a stop gap?

**Comment by jcfuller1** [comment]
Are the proper legal files now included with the build and distribution?

**Comment by nikhilgupta10** [comment]
@afisher1 @ntenney can we close this assuming @jcfuller1's question is answered. If not, what do we need to do?

**Comment by jcfuller1** [comment]
@afisher1 @ntenney - please verify that all of the above licenses are being distributed with the release.

**Comment by afisher1** [comment]
I just checked and they are there as well as the license files. closing issue.
