### ISSUE TITLE
VOLT_WATT inverter

### ISSUE THREAD

**Issue by jcfuller1** [gridlab-d/gridlab-d#1017]
Add VOLT_WATT feature (and other non-implemented Rule 21 / IEEE compliant) to the inverter.

**Comment by jcfuller1** [comment]
@temcdrm @afisher1  -  I believe this is completed?

**Comment by afisher1** [comment]
I just merged @temcdrm pull request on monday. I didn't realize this issue was attached to it. Closing issue.
