### ISSUE TITLE
Integrate HELICS application api in GridLAB-D

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1024]
Develop an object in GridLAB-D the utilizes the HELICS application API to allow GridLAB-D to operate as a federate in a HELICS co-simulation

**Comment by activeshadow** [comment]
@afisher1 any chance you have an idea of what's going on here?

**Comment by afisher1** [comment]
@activeshadow the --with-helics option needs to contain the path to where HELICS was installed not the linker flag, or a yes/no. Also GridLAB-D uses HELICS C++ shared library libhelics-shared.so. This library isn't built by default when compiling HELICS from source. You should make sure BUILD_CXX_SHARED_LIB is checked when building HELICS.

**Comment by afisher1** [comment]
I should actually close this issue as the work has been finished and merged back into develop.

**Comment by activeshadow** [comment]
> @activeshadow the --with-helics option needs to contain the path to where HELICS was installed not the linker flag, or a yes/no. Also GridLAB-D uses HELICS C++ shared library libhelics-shared.so. This library isn't built by default when compiling HELICS from source. You should make sure BUILD_CXX_SHARED_LIB is checked when building HELICS.
> 
Ahhh... this will likely do the trick! If not I’ll open a new issue. I’ll post back here either way. Thank you!

**Comment by activeshadow** [comment]
@afisher1 I'm still having issues compiling GridLAB-D with HELICS support, even after enabling the `BUILD_CXX_SHARED_LIB` option when compiling HELICS (which I confirmed does result in `libhelics-shared.so` being created). I've created issue #1148 for this.
