### ISSUE TITLE
Fix C/C++ Warnings during build

### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#1038]
A lot of these warnings need to be addressed and this might be a good time to take a look at them

**Comment by nikhilgupta10** [comment]
@ftuffner is this going to be addressed as part of the "Speedup" work you are doing? One of the interns made some progress on this but the progress was "buggy" so we did not move forward with her edits.

**Comment by dchassin** [comment]
It's certainly something we could/should look at while conduction the CEC work starting in June.

**Comment by trevorhardy** [comment]
feature/1091 may have features that haven't been merged into develop that could be useful.

**Comment by eberleim** [comment]
The majority of warnings have been resolved in the #1091 update and CMake build process. The remaining warnings require more significant structural changes to the application, and have been deferred to future revisions.
