### ISSUE TITLE
TMY3 temperature data is not being read in correctly

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1040]
Both TMY2 and TMY3 temperature is stored in tenths of a degree C. However, when it is a TMY3 file the temperature that is read in gets multiplied by 10 and converted to a integer. This shouldn't be happening. in TMY2 the temperature value is always a integer but in TMY3 the value is a float. The TMY3 is correctly read in as a float but shouldn't be converted to an integer.

**Comment by nikhilgupta10** [comment]
multiplied by 10 is deleted. string to int (Atoi) still needs to be done. committing changes to the issue.

**Comment by afisher1** [comment]
I'm actually wrong. TMY3 stores temperature in degrees C at a resolution of 0.1 degree. So the code is right to multiply by 10 but what should be done is the product should be rounded to the nearest whole number. So line 424 should be changed from:

tmp_tdb = (int)(atof(t_tdb)*10); 

to:

tmp_tdb = (int)(roundf(atof(t_tdb)*10.0));

**Comment by afisher1** [comment]
if This doesn't fix the problem then we shouldn't be trying to convert to an integer and we should use the float directly in the conversion from degrees C to degrees F using if tmy3 do this else if tmy2 do this.

**Comment by afisher1** [comment]
In all honesty converting the float to an integer is just a bad approach. In the end the value is a double. I am just now noticing we are doing the same for wind speed and precipitation. if tmy3 stores these values as floating point numbers then they should be read in and kept as floating point numbers. We definitely should be using more if( tmy3 ){} else if( tmy2){} cases rather than trying to get away with just one at the top of the function.

**Comment by afisher1** [comment]
The roundf() approach fixed the issue. closing the issue.
