### ISSUE TITLE
Add Timestamp Feature to GridLAB-D's FNCS Messages

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1042]
Yingying requested the ability to for a user to specify that the timestamp of the simulation when a FNCS message is published in GridLAB-D be included in the message as well.

I will add a property called include_timestamp such that when it's set to true the message payload looks like this:
```python
    '{
         "timestamp" : "mm-dd-yyyy hh:mm:ss",
         "value" : "value_string"
     }'
```
This will not break backwards compatibility.

**Comment by jcfuller1** [comment]
@afisher1 -  was this completed?  If not, is it a needed enhancement?

**Comment by afisher1** [comment]
It was actually needed for GridAPPS-D. I did add it in. I forgot I actually created an issue for it. Closing issue.
