### ISSUE TITLE
Support Reiteration from FNCS Co-Simulation

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1045]
Currently the way fncs_msg is written it prevents co-simulation reiterations. In order to allow for such reitierations changes must be made in the exec loop and in the fncs_msg object in the connection module. The proposed approach is to move the clock_update() function in the exec loop to before commit is executed and after the presync/sync/postsync passes. And allow the current time to be an acceptable return time from the fncs_broker in the fncs_msg object.

**Comment by ftuffner** [comment]
FNCS succeeded by HELICS.  Closing.
