### ISSUE TITLE
Voltage regulator issues warnings on tap limits when it shouldn't

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1051]
The voltage regulator tap control issues warnings on phases that aren't connected. A quick look through the code suggests that a review may be needed.  Another possible problem is that tap operations on unconnected phases are counted toward failure count.

**Comment by dchassin** [comment]
A fix for the erroneous warnings is available at https://github.com/dchassin/gridlabd/commit/9f52b9f252ed19964a0d1d135b3d93f5be6c0f9d

**Comment by afisher1** [comment]
I've merged the fix into develop. closing issue.
