### ISSUE TITLE
mysql module empty password handling is not working correctly

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1078]
The mysql module send an empty password string when password is set to "" instead of not using a password. This causes the server to think a password is being used when none is being used.

**Comment by eberleim** [comment]
@dchassin This issue should now be resolved by #1098, and the current behavior should conform to the MySQL spec for mysql_real_connect found [here](https://dev.mysql.com/doc/refman/8.0/en/mysql-real-connect.html). 
I'm going to close the ticket for now, however, if the problem persists on your end please reopen it.
