### ISSUE TITLE
#110 JAVA_HOME,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#110]
The glmjava project in the VS2005 solution relies on the $(JAVA_HOME) environment variable to locate the relevant jni.h and associated Java header files. This variable is not always properly being set.  

An example of what the value should be is \C:\Program Files\Java\jdk1.6.0_11\.  

,

**Comment by ftuffner** [comment]
Java support deprecated and for much older version of GLD.  Closing as part of ticket cleanup
