### ISSUE TITLE
polar vs rectangular form output inconsistency in recorder

### ISSUE THREAD

**Issue by kdarmenova** [gridlab-d/gridlab-d#1103]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [ ] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ ] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
I have a recorder for a substation meter that saves: 
~~~
property measured_voltage_A.real, measured_voltage_A.imag, measured_current_A.real, measured_current_A.imag, measured_power_A.real, measured_power_A.imag;
~~~
I modified the recorder to save: 
~~~
property measured_voltage_A, measured_current_A, measured_power_A;
~~~
When I compared the output for an identical gridlabd run the voltage/power polar form numbers do not match the rectangular form numbers. 

I used the following conversion (in python) to compute the rectangular to polar transform:
~~~
>>> R=np.sqrt(Re x Re + Im x Im)
>>> thetha = np.rad2deg(np.arctan(-Im/Re))
~~~
I also used the online converter to double check:
https://www.intmath.com/complex-numbers/convert-polar-rectangular-interactive.php

## Please provide the steps to reproduce.

I am using the distribution_system_basics.glm from the Tutorial:
~~~
object meter {     
      name substation_meter;     
      phases ABCN;     
      nominal_voltage 7216.88;     
      object recorder {
     	name substation_recorder;
     	file substation_data_ch.csv;
     	interval 60;
        property measured_voltage_A.real, measured_voltage_A.imag, measured_current_A.real, measured_current_A.imag, measured_power_A.real, measured_power_A.imag;
	};     
} 
~~~

## Please provide the exact error/warnining/failure message printed on the console.
~~~
timestamp,measured_voltage_A.real, measured_voltage_A.imag, measured_current_A.real, measured_current_A.imag, measured_power_A.real, measured_power_A.imag
2009-01-01 00:00:00 PST,+7215.59,-0.607896,+47.9882,-22.7537,+346277,+164152

timestamp,measured_voltage_A, measured_current_A, measured_power_A
2009-01-01 00:00:00 PST,+7155.78-0.744996d,+47.9882-22.7537j,+380039+24.6231d

~~~

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by dchassin** [comment]
That doesn't look right to me either.  It's as if the notation part of the complex property is being ignored by the recorder when it links to the property or reads it.

**Comment by jcfuller1** [comment]
Closing ticket as duplicate.  Please see ticket 887.

**Comment by kdarmenova** [comment]
I looked at Ticket 887 but I don't think this is the same issue. I am finding inconsistencies with the output voltage and power values. The polar form value does not match the rectangular form value so I don't know which one is correct and which one is not. There is accuracy lost in the conversion. Ticket 887 concerns the fact that the output produces both rectangular and polar outputs and contains i and/or j.

**Comment by dchassin** [comment]
Given the follow-on discussion between Dave Pinney and myself in #887, I have to agree with Jason's conclusion that these are fundamentally the same problem. They certainly will be solved by the same fix when it is developed, so we should either close or merge. Closing makes sense to me insofar as the new ticket does not add significant new information regarding the source of the problem or the form of the solution.  In fact the Sunhil's original write-up acknowledges that the issue identified may be indicative of further issues. This new ticket certainly fits that original comment.

I have added a ref in #887 to this ticket because of the possible additional validation case we could use provided we can identify how to automate the test.  That might be difficult to do but could be worthwhile if the fix is complicated and/or brittle (which it might very well be).

**Comment by ftuffner** [comment]
I think we need to look into this further before lumping it in with #887.  As @kdarmenova points out, the answers between the rectangular representation and polar one are not the same; e.g., +7155.78-0.744996d for voltage_A is 7155.78-93.04136j, which is not the value of +7215.59-0.607896j when the explicit .real and .imag were done.  The process of "triggering" the conversions (with the change to the recorder) may be altering something else in the system.  So the problem may not be the same as the recorder issue -- it might be with the meter or the system.

**Comment by dchassin** [comment]
I'm fairly confident we can fix recorder so it works as expected without changing anything that already works.  The issue of how/why other agents implicitly change the complex notation is independent of how the recorder reads the property--it's supposed to convert the property to what the user wants regardless of how it's stored internally.  I really think all this will be solved by using the appropriate convert API for properties in the way mysql recorder does.  Right now link_properties() just links the real or imaginary part, and read_properties just reads what is linked.  That's how it was done in the bad old days but now that method is completely wrong. 

This really does to a much more important discussion about what to do with this module: revise or replace? I vote for doing whichever is easier, but I'm not certain which is actually easier until we have decide what old capabilities we don't upgrade.  I'm thinking of "plot" and "memory", etc.
