### ISSUE TITLE
evcharger_det does not charge for some EVs after certain time

### ISSUE THREAD

**Issue by athlonshi** [gridlab-d/gridlab-d#1106]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
I have add evcharger_det objects to some houses based on the IEEE13nodes template. I have noticed through the output of SOC that some EVs do not charge after arriving home. 
evcharge_det profile looks like this
object evcharger_det {
	groupid EVs;
	name EV_13;
	parent house5C_tm_C_5_671;
	variation_mean 0.0;
	variation_std_dev 0.0;
	variation_trip_mean 0.0;
	variation_trip_std_dev 0.0;
	work_charging_available false;
	travel_distance 37.96;
	arrival_at_work 0755;
	duration_at_work 8.79 h;
	arrival_at_home 1642;
	duration_at_home 14.21 h;
	mileage_efficiency 3.85;
	maximum_charge_rate 6600;
	charging_efficiency 0.95;
	battery_size 16.0 kWh;
	configuration IS220;
	breaker_amps 100;
}

## Please provide the steps to reproduce.
The files are attached. Check for the EV_SOC.csv for SOC output

## Please provide the exact error/warnining/failure message printed on the console.

Warnings seem not relevant to the problem

## If possible, please provide any screenshots and other supporting information.

-----------------------------------------------------
[EV example.zip](https://github.com/gridlab-d/gridlab-d/files/2001453/EV.example.zip)

**Comment by afisher1** [comment]
Hello @athlonshi 

I was looking at your model and it appears as if your travel schedules basically add up to 0 time traveled between home and work and work and home. This could cause some unusual state behavior and be the reason why some of your ev's are not charging when they get home as it could be stuck in a transition state and not think it is home. Try leaving some travel time greater than 0 set up in your schedules (ie:  decrease your duration_at_work and duration_at_home by 20 minutes each).

**Comment by athlonshi** [comment]
Thanks a lot. That is indeed the problem. Now the model works as expected.
