### ISSUE TITLE
Validation broken when running on certain file systems in Linux

### ISSUE THREAD

**Issue by ntenney** [gridlab-d/gridlab-d#1117]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

While running on an xfs file system, --validate returns immediately and 0 tests are run. This is because of a known issue with readdir where the d_type is set to UNKNOWN unless the file system is created a certain way (which is not the default). The fix is to use lstat in these cases.

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
issue has been fixed and merged
