### ISSUE TITLE
Build error on macOS with node::defaults not found

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1134]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

The following compile error occurs on some macOS builds. This has been confirmed on a majority of SLAC macOS build systems over the past few weeks as the system get automatic upgrades from IT support.

~~~~
Undefined symbols for architecture x86_64:
  "node::defaults", referenced from:
      node::get_full_Y_matrix_offset() in powerflow_powerflow_la-node.o
      node::get_full_Y_all_matrix_offset() in powerflow_powerflow_la-node.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [powerflow/powerflow.la] Error 1
make: *** [all] Error 2
~~~~

## Please provide the steps to reproduce.

Checkout develop and build it with standard settings. Sometimes it happens, sometimes it doesn't.  We can't seem to figure out what exactly makes it occurs. 

The root cause is some (all?) the classes in powerflow don't use the standard "defaults" object template mechanism that modules are supposed to use to do fast array-style object creation. This is probably a good thing in the long run, because cloning objects in CPP is dangerous if the object uses virtual functions, even though it is very fast.  But not using "defaults" is still not officially supported in the C++ API.  I think that's where the problem comes from. 

I think the solution is to not use the C++ API call to get the address of the object's data. If we use PADDR(full_Y_matrix) and PADDR(full_Y_all_matrix) it should be ok for all compilers.

## Please provide the exact error/warnining/failure message printed on the console.

See above.

## If possible, please provide any screenshots and other supporting information.

N/A

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Merged branch in.  Included changes to residential/applicance.cpp as well, just to be consistent.
