### ISSUE TITLE
Add CCSI develop Transactive Energy Controller

### ISSUE THREAD

**Issue by Jacobhansens** [gridlab-d/gridlab-d#1157]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

Add the CCSI developed Transactive Energy Controller to GridLAB-D

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
It's been added.
