### ISSUE TITLE
Add External Reliability Event Handler.

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1162]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

The GridAPPS-D platform needs a way to insert scheduled and unschedule reliability events into the GridLAB-D simulation through a FNCS/HELICS co-simulation.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Included in v4.3 base code.  Believe it got merged in as part of another ticket.  Closing as part of ticket cleanup
