### ISSUE TITLE
property base_power of ZIPload:22 could not be set to 'LIGHTS*1.8752'

### ISSUE THREAD

**Issue by vireshpatel18** [gridlab-d/gridlab-d#1163]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by vireshpatel18** [comment]
I am using Keeler (Version 4.0). And I had downloaded master folder from this link
https://github.com/gridlab-d/gridlab-d

but when I try to run the program named dist_gen_battery_solar.glm from this link
http://gridlab-d.shoutwiki.com/wiki/GridLAB-D_Wiki:GridLAB-D_Tutorial_Chapter_6_-_Distributed_Generation

I get the error **property base_power of ZIPload:22 could not be set to 'LIGHTS*1.8752'** on line number 199.

**Comment by ftuffner** [comment]
The first three items of the bug report are a checklist -- you should really do the other two (especially contributing.md).

The file you mentioned works fine under both 4.0 and 4.1 (verified just now).

Can you provide the full output of the command:
`gridlabd --version`
as well as information on your operating system?

As a standard caveat, we highly encourage users to be building the latest version of GridLAB-D, under /release/RC4.1

**Comment by vireshpatel18** [comment]
I have run command at result is:-
Microsoft Windows [Version 10.0.17134.472] (c) 2018 Microsoft Corporation. All
rights reserved. C:\Users\AMI_SI-HAS>gridlabd --version GridLAB-D 4.0.0-17322 (
https://github.com/gridlab-d/gri¬C) 64-bit WINDOWS RELEASE  





On Thu, Jan 3, 2019 3:00 AM, Frank Tuffner notifications@github.com  wrote:
The first three items of the bug report are a checklist -- you should really do
the other two (especially contributing.md).

The file you mentioned works fine under both 4.0 and 4.1 (verified just now).

Can you provide the full output of the command:
gridlabd --version
as well as information on your operating system?

As a standard caveat, we highly encourage users to be building the latest
version of GridLAB-D, under /release/RC4.1

**Comment by ftuffner** [comment]
Prior versions.  Probably was a v4.0 bug fix.  Closing as part of ticket cleanup
