### ISSUE TITLE
Potential Undefined Behavior in object.c

### ISSUE THREAD

**Issue by eberleim** [gridlab-d/gridlab-d#1167]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
`set_rank` and `_set_rankx` in object.c are both declared as having `static int` return type, but both exit flow control without returning any value in at least a portion of run cases. 

According to the C11 standard (2018 standard is behind paywall, but this definition should not have changed):
> If the } that terminates a function is reached, and the value of the function call is used by
the caller, the behavior is undefined.
[N1570, C11 Standard, Page 157, item 12](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf)

Based on the standard, and the current use of the functions listed, the current behavior of Gridlab-d may be undefined. 

## Please provide the steps to reproduce.
n/a - does not currently cause an error.

## Please provide the exact error/warning/failure message printed on the console.
n/a - does not currently cause an error.

## If possible, please provide any screenshots and other supporting information.
This should be a fairly trivial bug to actually fix, but it is important that we're returning values that are sane for all cases, so I've tagged a number of individuals who may be able to provide feedback as to "safe/sane" values to select as the default return case.

-------------------------------------------------------------------------------------------------------------

**Comment by eberleim** [comment]
Update: this issue is likely why GridLAB-D builds using gcc-8 fail validation when optimization is turned on.

**Comment by dchassin** [comment]
I believe it’s supposed to return obj->rank.
