### ISSUE TITLE
MATLAB R2018a does not appear to work with GridLAB-D

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1168]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Trying to compile GridLAB-D with MATLAB R2018a (and R2018b) results in the error output in the attached PNG (copying and pasting the compiler output is not formatting well inside Git, for whatever reason).

## Please provide the steps to reproduce.
Compile GridLAB-D while trying to include MATLAB.  An example configure command was:

./configure --build=x86_64-w64-mingw32 --prefix=$PWD/install64 --with-xerces=/mingw64/bin --with-matlab=C:/PROGRA~1/MATLAB/R2018a  --enable-silent-rules 'CFLAGS=-O2 -w' 'CXXFLAGS=-O2 -w' 'LDFLAGS=-O2 -w'

## Please provide the exact error/warnining/failure message printed on the console.
See attached
![matlab_r2018a_error](https://user-images.githubusercontent.com/11561302/51863531-1f10ba80-22f6-11e9-8aee-b388674879cb.png)

## If possible, please provide any screenshots and other supporting information.
Also shown in SourceForge topic at https://sourceforge.net/p/gridlab-d/discussion/842562/thread/5bafe6f6/

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Still works with 2015a, so it's likely Mathworks changed the headers (and prototypes?) a little, which is what is causing the issue.

**Comment by ftuffner** [comment]
Mathworks apparently changed how complex number arrays are handled, to make things more compatible with other software (whether they were separate real/imaginary arrays, or interleaved).  Luckily, you can force it to use a legacy mode right now, but I'm not sure how we'll want to handle this in the future.

To do the work around, the compiler definition of MATLAB_DEFAULT_RELEASE to R2017b.  An example include command could be:
`./configure --build=x86_64-w64-mingw32 --prefix=$PWD/install64 --with-xerces=/mingw64/bin --with-matlab=C:/PROGRA~1/MATLAB/R2018a  --enable-silent-rules 'CFLAGS=-O2 -w -DMATLAB_DEFAULT_RELEASE=R2017b' 'CXXFLAGS=-O2 -w -DMATLAB_DEFAULT_RELEASE=R2017b' 'LDFLAGS=-O2 -w'`

I'll put an update on the wiki page for this, but again, we'll need to figure out how we want to handle it going forward.

**Comment by afisher1** [comment]
Native MATLAB support is deprecated please use HELICS for interfacing with MATLAB and GridLAB-D. Closing.
