### ISSUE TITLE
Windows installer with HELICS

### ISSUE THREAD

**Issue by rookscody** [gridlab-d/gridlab-d#1170]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
In future releases of the GridLAB-D Windows installer, an option to install with HELICS (or the other components) would be incredibly useful (especially for the computer science novices). 

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by kdheepak** [comment]
I second this, it would be really nice to get an installer, especially on Windows, so that users don't have to go through the hassle of installing GridLAB-D from source with dependencies like HELICS (See #1171).

**Comment by ftuffner** [comment]
Prior version.  Ability to select HELICS/FNCS/MATLAB/MySQL connections included in v4.3 release
