### ISSUE TITLE
Implement multi-layer waterheater model

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1175]
This is an enhancement ticket to impelement the multi-layer waterheatermodel into waterheater.h and waterheater.cpp

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

NA

## Please provide the steps to reproduce.

NA

## Please provide the exact error/warnining/failure message printed on the console.

NA

## If possible, please provide any screenshots and other supporting information.

NA

-------------------------------------------------------------------------------------------------------------

**Comment by trevorhardy** [comment]
@afisher1, Is this the one from DSO+T?

**Comment by afisher1** [comment]
Yes this is in there already. closing
