### ISSUE TITLE
Modify GridLAB-D so it can compile with the version 2.1 of HELICS

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1179]
currently GridLAB-D cannot compile with the develop branch of HELICS. This branch will attempt to find the cause fix it so GridLAB-D can compile with the develop branch of HELICS.

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
There are undefined references to the jsoncpp library that keep cropping up when compiling with the develop branch of HELICS.

## Please provide the steps to reproduce.
compile with a develop build of HELICS

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
This is now to modify GridLAB-D to work with release 2.1 of HELICS

**Comment by kdheepak** [comment]
Is there instructions posted somewhere for this? Can you share the link here?

**Comment by ftuffner** [comment]
Prior version.  v4.3 compiles with HELICS 2.7.x, so this was resolved a while ago. Closing for issue/ticket cleanup
