### ISSUE TITLE
Cannot figure out how to run my glm files

### ISSUE THREAD

**Issue by Renison77** [gridlab-d/gridlab-d#1188]
I am an undergrad student and fairly new to command line interface working. So far I have figured out how to compose various programs. However, I do not know how to run the glm files. And also is there a specific path where the glm file has to be before running  through the console?

eg if i have to run the sample files stored in gridlabd/samples, in the console i type path/gridlabd.exe --example.glm. I know it is incorrect but cannot figure out what to do.

**Comment by afisher1** [comment]
please see our guide here. http://gridlab-d.shoutwiki.com/wiki/GridLAB-D_Wiki:GridLAB-D_Tutorial_Chapter_0_-_Introduction

**Comment by ftuffner** [comment]
Prior version and no updates in long time.  Assuming resolved and closing for issue/ticket cleanup
