### ISSUE TITLE
HOW TO SOLVE THIS install wrong

### ISSUE THREAD

**Issue by lhx20070322** [gridlab-d/gridlab-d#1189]
climate/climate.cpp: In member function 'void climate::init_cloud_pattern()':
climate/climate.cpp:1071:13: error: expected unqualified-id before '(' token
   if (!std::isnan(longitude) && !std::isnan(latitude)) {
             ^
climate/climate.cpp:1071:39: error: expected unqualified-id before '(' token
   if (!std::isnan(longitude) && !std::isnan(latitude)) {
                                       ^
climate/climate.cpp: In member function 'TIMESTAMP climate::presync(TIMESTAMP)':
climate/climate.cpp:2053:60: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
    GL_THROW("climate::sync -- unable to resolve localtime!");
                                                            ^
climate/climate.cpp:2221:65: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
     GL_THROW("climate::sync -- unrecognized interpolation mode!");
                                                                 ^
make[1]: *** [climate/climate_climate_la-climate.lo] Error 1
make[1]: Leaving directory `/C/Projects/gridlab-d/gridlab-d'
make: *** [install] Error 2

**Comment by afisher1** [comment]
Hi which branch are you trying to build and on what OS?

This error is due to you not setting up the compiler to use c++11 or greater. If on linux this requires that you gcc and g++ be 6.0 or newer and setting -std=c++11 in your CXXFLAGS variable. If you are on Mac you cannot compile 4.1or 4.2 of GridLAB-D with clang.

**Comment by ftuffner** [comment]
Prior version and no updates in long time.  Assuming resolved and closing for issue/ticket cleanup
