### ISSUE TITLE
Distributed Wind Power Curve Update

### ISSUE THREAD

**Issue by areiman** [gridlab-d/gridlab-d#1190]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

In recent years, designs for distributed wind turbines have been trending towards larger blade diameters for a given electric machine rating. the coefficient of performance curve implementation will be enhanced to enable use of modern power curves.

**Comment by ftuffner** [comment]
Merged in long ago.  Likely left open for any outstanding issues and forgotten.  Closing.
