### ISSUE TITLE
Modifications to 3-phase house of feature/1173 (#1185)

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1202]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Connection of 3-phase house in #1185 needs to be adjusted to be more inline with how normal house connections (triplex) work.  Putting this in a separate issue/ticket for pull-request merging, since that feature branch is being actively used for projects.

## Please provide the steps to reproduce.
N/A

## Please provide the exact error/warnining/failure message printed on the console.
No errors noted, just differences in code interfacing.

## If possible, please provide any screenshots and other supporting information.
N/A

-------------------------------------------------------------------------------------------------------------

**Comment by temcdrm** [comment]
I think feature/1173 was opened only for this issue of three-phase houses.  We have to continue using that branch for TESP (and DSOT?) until the review comments have been addressed.  Not aware of any other projects using this branch.

**Comment by ftuffner** [comment]
Closing the ticket out.  Per Tom's note above, #1185 was the original issue, so if there are any problems with this implementation, we'll handle them there.
