### ISSUE TITLE
Remove boost dependencies from install with helics

### ISSUE THREAD

**Issue by kdheepak** [gridlab-d/gridlab-d#1203]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

https://github.com/gridlab-d/gridlab-d/blob/ed817d27cc22bad8bc13184679882581d7276bfe/configure.ac#L498-L509

The above lines need to be updated to not include boost in the build steps.

See discussion [here](https://gitter.im/GMLC-TDC/HELICS?at=5dcb7cff091dd14a0eade2bc) for more context.

**Comment by eberleim** [comment]
Resolved while fixing other autoconfig properties.

**Comment by kdheepak** [comment]
Great!
