### ISSUE TITLE
Failure to compile with HELICS support

### ISSUE THREAD

**Issue by esilksel** [gridlab-d/gridlab-d#1204]
Initial Checklist prior to submitting the issue. Check the below boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
I provided the "--with-helics=" argument to ./configure, pointing it to /home/username/.local/helics-2.3.0; when compiling. The compilation fails, citing two instances of `invalid operands of types 'std::size_t {aka long unsigned int}' and 'double' to binary 'operator<<'`, both in relation to HELICS messages.

## Please provide the steps to reproduce.
I was following [these instructions](https://github.com/GMLC-TDC/HELICS-Tutorial/blob/master/setup/README.md), specifically:
1. Install HELICS following [these instructions](https://helics.readthedocs.io/en/latest/installation/linux.html#building-helics-with-python-support). Was on https://github.com/GMLC-TDC/HELICS/commit/b6cf2eecb1958421d53044a182e442646a5b07d7 at time of writing.
2. Install HELICS-Runner using [these instructions](https://github.com/GMLC-TDC/helics-cli)
3. Clone this repo, checkout the develop branch, make a "build" directory, and from within it run
``` 
./configure --with-helics=/home/ericsilk/.local/helics-2.3.0 --enable-silent-rules "CFLAGS=-g -O0 -w" "CXXFLAGS=-g -O0 -w -std=c++14" "LDFLAGS=-g -O0 -w"
```
Was on commit ed817d27cc22bad8bc13184679882581d7276bfe at time of writing.

## Please provide the exact error/warnining/failure message printed on the console.
```
/bin/bash -c "source utilities/build_number . gldcore/build.h"
Updating gldcore/build.h: revision 18186 (ed817d27:develop:Mod)
/home/ericsilk/Documents/HELICS_Project/gridlab-d
make  all-am
make[1]: Entering directory '/home/ericsilk/Documents/HELICS_Project/gridlab-d'
  CXX      connection/connection_connection_la-helics_msg.lo
In file included from /usr/include/c++/7/bits/hashtable.h:35:0,
                 from /usr/include/c++/7/unordered_map:47,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/external/cereal/archives/../cereal.hpp:36,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/external/cereal/archives/portable_binary.hpp:32,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueConverter_impl.hpp:20,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueConverter.hpp:65,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueFederate.hpp:11,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/CombinationFederate.hpp:10,
                 from connection/helics_msg.h:21,
                 from connection/helics_msg.cpp:16:
/usr/include/c++/7/bits/hashtable_policy.h: In member function ‘std::size_t std::__detail::_Power2_rehash_policy::_M_next_bkt(std::size_t)’:
/usr/include/c++/7/bits/hashtable_policy.h:563:40: error: invalid operands of types ‘std::size_t {aka long unsigned int}’ and ‘double’ to binary ‘operator<<’
       const auto __max_bkt = size_t(1) << (__max_width * __CHAR_BIT__ - 1);
                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:4574: recipe for target 'connection/connection_connection_la-helics_msg.lo' failed
make[1]: *** [connection/connection_connection_la-helics_msg.lo] Error 1
  CXX      connection/connection_connection_la-init.lo
In file included from /usr/include/c++/7/bits/hashtable.h:35:0,
                 from /usr/include/c++/7/unordered_map:47,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/external/cereal/archives/../cereal.hpp:36,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/external/cereal/archives/portable_binary.hpp:32,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueConverter_impl.hpp:20,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueConverter.hpp:65,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/ValueFederate.hpp:11,
                 from /home/ericsilk/.local/helics-2.3.0/include/helics/application_api/CombinationFederate.hpp:10,
                 from connection/helics_msg.h:21,
                 from connection/init.cpp:16:
/usr/include/c++/7/bits/hashtable_policy.h: In member function ‘std::size_t std::__detail::_Power2_rehash_policy::_M_next_bkt(std::size_t)’:
/usr/include/c++/7/bits/hashtable_policy.h:563:40: error: invalid operands of types ‘std::size_t {aka long unsigned int}’ and ‘double’ to binary ‘operator<<’
       const auto __max_bkt = size_t(1) << (__max_width * __CHAR_BIT__ - 1);
                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:4595: recipe for target 'connection/connection_connection_la-init.lo' failed
make[1]: *** [connection/connection_connection_la-init.lo] Error 1
/bin/bash -c "source utilities/build_number . gldcore/build.h"
Updating gldcore/build.h: revision 18186 (ed817d27:develop:Mod)
/home/ericsilk/Documents/HELICS_Project/gridlab-d
  CXX      gldcore/link/engine/gldcore_link_engine_glxengine_la-engine.lo
  CXXLD    gldcore/link/engine/glxengine.la
  CC       gldcore/gridlabd-version.o
  CXXLD    gridlabd
make[1]: Target 'all-am' not remade because of errors.
make[1]: Leaving directory '/home/ericsilk/Documents/HELICS_Project/gridlab-d'
Makefile:1612: recipe for target 'all' failed
make: *** [all] Error 2

```

## If possible, please provide any screenshots and other supporting information.

I'm on (K)Ubuntu 18.04. gcc version 7.4.0. 
Forcing the usage of clang (CC=clang CXX=clang++, version is 6.0.0-1ubuntu2), there is one similar error but also:
```
cannot pass object of non-trivial type 'std::__cxx11::string'
    (aka 'basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
        gl_verbose("helics_msg::init(): registering publishing endpoint: %s", gld_ep_pub->name);
                                                                                          ^
```
-------------------------------------------------------------------------------------------------------------

**Comment by esilksel** [comment]
Per some [some feedback on StackOverflow](https://stackoverflow.com/questions/59058184/auto-deducing-incorrect-type-in-hashtable-policy-h/59143165#59143165) it appears the underlying cause of this is the inclusion of `platform.h`, causing `std::min` within `hasthable_policy.cpp` to be replaced by `std::fmin`, which can only return type double, hence the error.

**Comment by trevorhardy** [comment]
@eberleim, if this something you have the time to tackle?

**Comment by esilksel** [comment]
Short term fix I've done is to just change the `min`/`max` to `MIN`/`MAX` and fix the resulting complaints from the compiler. This feels less than ideal, so I'm looking into a few other options.

**Comment by esilksel** [comment]
Alright, so far as I can see the "min" and "max" macros are only used in 3 files:

- `tape/memory.c`
- `gldcore/object.c`
- `gldcore/unit.c`

Is there a historical reason for this macro having been included in `platform.h`? `fmin` and `fmax` seem to be consistent across platforms, with the only noteworthy difference being that some implementations may enforce -0.0 being less than 0.0, but its not required.

Proposed fixes:

- Replace existing `min`/`max` calls with a project specific macros, such as `gld_min`/`gld_max`
- Replace existing `min`/`max` calls with their respective `fmin`/`fmax` calls and do away with the macro
- Add a separate header, e.g. `minmax.h` with a macro (either the same or one using `__typeof__` magic), and only include this in the source files that require it

**Comment by eberleim** [comment]
Regarding the `min`/`max` problem, to minimize conflicts when merging back in the feature/1091 branch where this is already fixed, it would be best to pursue option 2 (eliminate macros, use native calls), replacing calls in the C code with fmin, and calls in the C++ code with std::min which is templated and takes floats. 

I'll try to get this sorted out today or tomorrow as time allows.

**Comment by eberleim** [comment]
@esilksel Sorry for the delay on this, it unexpectedly caused brought up some windows platform build issues not directly related to this bug. 
I believe the current change on branch [bugfix/1204 @ 9a7a1edf82c17fc655ba82b54614d2ff66e99131](https://github.com/gridlab-d/gridlab-d/commit/9a7a1edf82c17fc655ba82b54614d2ff66e99131) should resolve the naming problem. 

I was still unable to complete the build process, because of an undefined reference issue, but I'm as-of-yet unsure if it is a HELICS issue or a GridLAB issue, so I will continue to troubleshoot.

**Comment by eberleim** [comment]
It looks like my build issues were local to my platform, this issue should now be fixed. 
I'll create a PR with these changes back to develop.

**Comment by esilksel** [comment]
Much appreciated, let me give building it a shot as well on my machine. Would you prefer feedback regarding that on this thread or the PR?

**Comment by eberleim** [comment]
@esilksel either one is fine.
The PR is now linked.
