### ISSUE TITLE
Throwing in solver_nr: "Failure to construct single/double phase line indices"

### ISSUE THREAD

**Issue by esilksel** [gridlab-d/gridlab-d#1206]
Initial Checklist prior to submitting the issue. Check the below boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Using the IEEE 8500 node test feeder GLM, generated by the Matlab scripts [here](https://github.com/gridlab-d/tools/tree/master/IEEE%20Test%20Models/8500node) causes an error which prevents execution on Ubuntu (but not Windows).

## Please provide the steps to reproduce.

- Be on a Linux machine (tested on Ubuntu 18.04)
- Clone the repo and check out the `develop` branch, commit `afa77fdb` (most recent).
- Build according to the Wiki instructions
    - Both with or without HELICS support
    - Both at optimization level 0 or 3 (other levels untested)
- Run the generation scripts found in the aforementioned repository
    - Note that the output directories may need to be adjusted
- Place `schedules.glm`, `recorders.glm`, and the generated `IEEE_8500node_whouses_NR.glm` in the same directory
- Run `gridlabd IEEE_8500node_whouses_NR.glm`

See [here](https://gist.github.com/esilksel/0ec5cb5f34d56a176c332aa86a1cabf5) for copies of the files in question (be warned, they're quite large).

## Please provide the exact error/warning/failure message printed on the console.

    WARNING  [INIT] : object name '1515A' does not follow strict naming rules and may not link correctly during load time
    WARNING  [INIT] : last warning message was repeated 156 times
    WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
    WARNING  [INIT] : waterheater::init() : height and diameter were not specified, defaulting to 3.78 ft
    ERROR    [2000-09-01 12:00:00 PDT] : sync_node(obj=20740;HVMV_Sub_HSB): NR: Failure to construct single/double phase line indices.
    ERROR    [2000-09-01 12:00:00 PDT] : 2000-09-01 12:00:00 PDT: object HVMV_Sub_HSB stopped its clock (exec)!
    ERROR    [2000-09-01 12:00:00 PDT] : exec halted: synchronization failed
    FATAL    [2000-09-01 12:00:00 PDT] : shutdown after simulation stopped prematurely
    FATAL    [2000-09-01 12:00:00 PDT] : environment startup failed: Success

The relevant code is found at line 2064 in `powerflow/solver_nr.cpp`. When modified to print the checked values upon failure, I get:

    ERROR    [2000-09-01 12:00:00 PDT] : sync_node(obj=20740;HVMV_Sub_HSB): NR: Failure to construct single/double phase line indices.
    index: 0
    index_b: -1
    size: 1
    size_b: -1
    size_c: 1

## If possible, please provide any screenshots and other supporting information.

Built on Ubuntu 18.04. Most interestingly, this does NOT occur when running on the latest Windows release: `GridLAB-D 4.1.0-17823 (Lugo [0753b96c:release/RC4.1:ModƒE) 64-bit WINDOWS RELEASE`

Will test the same version on Linux if desired.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@esilksel It isn't clear in the description, but which branch are you using in Ubuntu?  Are you building off of /develop, or /master, or something else?  Also, if you can try it with release/v4.2 under Ubuntu, that could be helpful.

I think I see the same issue under /develop (both in Linux and Windows), but want to verify that's what you are using.

**Comment by esilksel** [comment]
I'm on the develop branch on Ubuntu. I haven't taken the time to get the build system on Windows up so I can't immediately verify that its also the case on Windows. I've built release/v4.2, which reports the following version:

    gridlabd --version
    GridLAB-D 4.2.0-18111 (McNary [86e34f97:release/v4.2]) 64-bit LINUX RELEASE

But, I get a different error:

    gridlabd IEEE_8500node_whouses_NR.glm 
    WARNING  [INIT] : object name '1515A' does not follow strict naming rules and may not link correctly during load time
    WARNING  [INIT] : last warning message was repeated 156 times
    WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
    WARNING  [INIT] : waterheater::init() : height and diameter were not specified, defaulting to 3.78 ft
    ERROR    [2000-09-01 12:00:00 PDT] : exec halted: read lock timeout
    FATAL    [2000-09-01 12:00:00 PDT] : shutdown after simulation stopped prematurely
    FATAL    [2000-09-01 12:00:00 PDT] : environment startup failed: Success
    Model profiler results
    ======================
    
    Class            Time (s) Time (%) msec/obj
    ---------------- -------- -------- --------
    house              2.498     80.8%      1.0
    node               0.399     12.9%      0.2
    climate            0.076      2.5%     76.0
    triplex_node       0.040      1.3%      0.0
    overhead_line      0.028      0.9%      0.0
    ZIPload            0.018      0.6%      0.0
    waterheater        0.012      0.4%      0.0
    triplex_line       0.010      0.3%      0.0
    transformer        0.008      0.3%      0.0
    capacitor          0.003      0.1%      0.8
    ================ ======== ======== ========
    Total              3.092    100.0%      0.1
    
    WARNING  [2000-09-01 12:00:00 PDT] : last warning message was repeated 2439 times

Anything I can do to get a more verbose failure?

**Comment by ftuffner** [comment]
@esilksel Thanks for the information - this is helpful.  "Unfortunately" (fortunately?), I'm seeing identical issues to what you've posted above in /develop and release/4.2 under Ubuntu.  I'm actually going to split the second issue off into a separate item, since I'm guessing it is something else.

This at least confirms where the fix needs to be.  I'll get to work on seeing if I can see what has changed here or what is causing problems on Ubuntu (and potentially other systems).  The holiday season may delay the fix a little bit, if it ends up being something major.

As a final "information item", just in case, can you provide the version of GCC and G++ you're using to compile these?  I've noticed some issues with GCC-8 and GCC-9 with our Linux and Mac builds (different from this issue), so that may be another data point for our testing/debugging.

**Comment by ftuffner** [comment]
Second issue (read lock) split off into #1208

**Comment by esilksel** [comment]
Sure thing:

    gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
    g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

As an extra data point, I tried forcing the use of clang (passing `"CC=/usr/bin/clang" "CXX=/usr/bin/clang++"` to the configure script) and I get a compilation error in powerflow relating to an undefined reference (`node::defaults()`) on both `develop` and `release/v4.2`. I can post those details if you'd like, but for now I can't verify the same behavior with a different compiler, unfortunately.

As for the holiday season, no worries, things are sure to slow down around here as well.

**Comment by ftuffner** [comment]
Thanks @esilksel.  Clang has some known issues.  There are some fixes in feature/1091 that can enable it to work sometimes, but Clang support is something we're hoping to more reliably handle when we finish a GridLAB-D core rework.  For now, GCC is the "known stable/good" compiler for all platforms, except when things break, like this.

**Comment by ftuffner** [comment]
Issue appears to be related to some "recent" switch_object.cpp changes and the nature of the IEEE 8500-node.  Its "strictly radial" only due to open switches - topologically, it isn't, which is confusing the algorithm with the changes.  Figuring out how to fix it.

**Comment by esilksel** [comment]
Any updates?

**Comment by ftuffner** [comment]
@esilksel No immediate updates.  People are just coming back from the holidays.  I'm hoping to pick it back up later today or next week sometime.

**Comment by esilksel** [comment]
Sounds good, thank you!

**Comment by ftuffner** [comment]
@esilksel I believe I've fixed this in a recent code commit.  It's under bugfix/1206, but I'm going to submit a pull request to get it into /develop.  You can either checkout and try bugfix/1206, or just wait until it merged with /develop.

**Comment by esilksel** [comment]
Seems to be only showing the additionally mentioned "read lock timeout" now, which is tracked in #1208.

We appreciate the time and effort on this!

**Comment by ftuffner** [comment]
@esilksel Thanks for confirming it worked.  We'll close this issue once the pull request gets integrated.

We have some ideas on #1208 and will hopefully get to work on it shortly.

**Comment by ftuffner** [comment]
Successfully merged into /develope
