### ISSUE TITLE
runtime class no such file or directory

### ISSUE THREAD

**Issue by Timothy71** [gridlab-d/gridlab-d#1207]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [ ] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ ] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

when using runtime class, it said no such file or directory, it can't include the gridlabd.h
i have checked the environment path but found nothing

#set verbose=1
#set debug=1
#define include=C:\GridLAB-D\rt
clock {
	timezone PST+8PDT;
	starttime '2001-01-01 00:00:00';
	stoptime '2001-01-02 00:00:00'; 
}

// Create a class called helloworld that displays the message "Hello World" on the command prompt
class helloworld {
	intrinsic create(object parent) {
		return SUCCESS;
	};
	intrinsic init(object parent) {
		return SUCCESS;
	};
	intrinsic sync(timestamp t0, timestamp t1) {
		gl_output("Hello World");
		return TS_NEVER;
	};
}

object helloworld {
}

## Please provide the steps to reproduce.
C:\GridLAB-D>gridlabd runtime.glm
   ... C:\GridLAB-D\etc\tzinfo.txt loaded ok
   ... class helloworld registered ok
   ... writing inline code to 'C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp'
   ... compiling inline code from 'C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp'
   ... compile command: [g++ -w -g -O0 -m64  -fPIC -c "C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp" -o "C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.o"]
DEBUG [INIT] : Running 'g++ -w -g -O0 -m64  -fPIC -c "C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp" -o "C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.o"' in 'C:\GridLAB-D'
C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp:7:10: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>

## Please provide the exact error/warnining/failure message printed on the console.

C:\Users\Timothy\Local Settings\Temp\gridlabd/helloworld.cpp:7:10: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@Timothy71 You're probably missing an environmental variable.  You can try setting it via the GLM, but it may be easier to try it under the command line first.  With a new command prompt, try:

`set CXXFLAGS=-IC:/FOLDER_TO_H`

where "FOLDER_TO_H" is the location of your gridlabd.h file in your install (it probably is C:/GridLAB-D/share, but I don't have an installed copy readily available to test this).  Once this is set, the runtime compiler will probably work.

**Comment by Timothy71** [comment]
> @Timothy71 You're probably missing an environmental variable. You can try setting it via the GLM, but it may be easier to try it under the command line first. With a new command prompt, try:
> 
> `set CXXFLAGS=-IC:/FOLDER_TO_H`
> 
> where "FOLDER_TO_H" is the location of your gridlabd.h file in your install (it probably is C:/GridLAB-D/share, but I don't have an installed copy readily available to test this). Once this is set, the runtime compiler will probably work.

My gridlabd.h is in D:/GridLAB-D/GridLAB-D/rt
I have tried this command
set CXXFLAGS=-IC:/D:/GridLAB-D/GridLAB-D/rt
but it didn't work, the problem is same

**Comment by ftuffner** [comment]
@Timothy71 The "C" part of the statement is the drive letter.  So your command should probably be:

`set CXXFLAGS=-ID:/GridLAB-D/GridLAB-D/rt`

**Comment by Timothy71** [comment]
@ftuffner Thanks a lot, the problem is solved.
