### ISSUE TITLE
Ubuntu throws a "read lock timeout" error when running an IEEE 8500-node system

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1208]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
When running the 8500-node system from tools/IEEE Test Models/8500node under Ubuntu (18.04 and 19.10), it fails with a "read lock timeout" error.  This does not occur on Windows, nor does it seem to happen in /develop (but another issue interferes there).

## Please provide the steps to reproduce.
Generate the 8500-node system, per the notes in #1206, then run it under Ubuntu.  It should fail at the start of execution with a "read lock timeout" error.

## Please provide the exact error/warnining/failure message printed on the console.
From #1206, but verified on my end as well:

    WARNING  [INIT] : object name '1515A' does not follow strict naming rules and may not link correctly during load time
    WARNING  [INIT] : last warning message was repeated 156 times
    WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
    WARNING  [INIT] : waterheater::init() : height and diameter were not specified, defaulting to 3.78 ft
    ERROR    [2000-09-01 12:00:00 PDT] : exec halted: read lock timeout
    FATAL    [2000-09-01 12:00:00 PDT] : shutdown after simulation stopped prematurely
    FATAL    [2000-09-01 12:00:00 PDT] : environment startup failed: Success

## If possible, please provide any screenshots and other supporting information.
See #1206 discussions for some additional detail.

-------------------------------------------------------------------------------------------------------------

**Comment by esilksel** [comment]
Any updates on this issue?

**Comment by ftuffner** [comment]
@esilksel We thought we had fixed it with another pull-request/issue, but that doesn't appear to be the case.  We'll try to get back to this and see if we can figure it out, but it may not be until next week.

**Comment by leduytanjaist2016** [comment]
I got the same issue,
The code work well on MacOS,
But there is the  same problem in Ubuntu,

**Comment by ftuffner** [comment]
Code update and check to prevent capacitor from being associated with the "to" end of a remote link implemented and merged into /develop.  Closing.
