### ISSUE TITLE
HELICS-GLD - Enable the ability to swap between QSTS and deltamode

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1209]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Currently, HELICS and GridLAB-D communications are locked into a "fixed timestep".  HELICS interactions with GridLAB-D can either be only QSTS, or only deltamode.  Swapping between them is not supported, at this time.

There is theoretically an API call in HELICS to adjust the update timestep that could be used.  It may be as simple as exposing/interfacing with this, and then adding the appropriate code in GridLAB-D.

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
The helics_msg object does have the ability to handle transitions from QSTS. unless I'm missing something in my code.

**Comment by ftuffner** [comment]
Appears to have been fixed somewhere along the way or was user error back when reported.  Confirmed with an example that GLD will successfully go in and out of deltamode
