### ISSUE TITLE
ERROR running tutorial example/solutions: ERROR : schedule_recompile(SCHEDULE *sch='{name=residential-dishwasher-default, ...}') error recomputing index

### ISSUE THREAD

**Issue by unl1m173d** [gridlab-d/gridlab-d#1212]
## Please describe what was the cause of the issue?

Trying to run an example solutions file as provided in the tutorial module #4 but gridlabd complains of a schedule_recompile error relating to residential-dishwasher-default then exits.

Running gridlabd 4.1.0-17823 (Lugo [0753b96c:release/RC4.1ModŸE) 64-bit WINDOWS RELEASE

Issue also occurs under Linux version, however linux version also segfaults!!
GridLAB-D 4.1.0-18109 (Lugo [46541cb8:master:Mod]) 64-bit LINUX RELEASE

## Please provide the steps to reproduce.
1. Download and extract gridlabd tutorial Module #4: https://github.com/gridlab-d/course/blob/master/OnlineTutorial_v22/Module4.zip
2. Navigate to folder 5.1 Market Solutions
3. Run exercise_5_1_1.glm

## Please provide the exact error/warnining/failure message printed on the console.

ERROR  [2001-01-01 00:00:00 EST] : schedule_recompile(SCHEDULE *sch='{name=residential-dishwasher-default, ...}') unable to find value
ERROR  [2001-01-01 00:00:00 EST] : schedule_recompile(SCHEDULE *sch='{name=residential-dishwasher-default, ...}') error recomputing index

Segfaults under linux.

## If possible, please provide any screenshots and other supporting information.
![image](https://user-images.githubusercontent.com/5506570/71382307-5ab71180-25a5-11ea-9c8a-10e5a81cddc0.png)

![image](https://user-images.githubusercontent.com/5506570/71382822-abc80500-25a7-11ea-82a7-3e4ae6b9226a.png)

**Comment by ftuffner** [comment]
@unl1m173d Can you download a fresh copy of 4.1, or better yet, a copy of 4.2 from [the GridLAB-D.org downloads page](https://www.gridlabd.org/downloads.stm).  I am not able to replicate this error in version 4.1 or 4.2, but the version of 4.1 (for Windows) looks different.

For the Linux segfault issue, that is a known issue documented in #1193 that we have a solution for, but still haven't fully pushed.

**Comment by ftuffner** [comment]
I'll note that if the `stoptime` value is changed to far in the future (or deleted), it can cause that error.  There's a separate issue we're documenting now on that.

**Comment by ftuffner** [comment]
Likely another expression of #1218, now that it has been dug into a little more.  Main tracking of issue in that ticket.

**Comment by ftuffner** [comment]
Fixed as part of PR #1219.  Closing.
