### ISSUE TITLE
MATLAB Link: double_array functionality

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1217]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
The double_array type does not appear to work in the MATLAB link.  Some initial code (possibly stubs) are present, but the link does not seem to want to exchange the information.  

## Please provide the steps to reproduce.
Run the test_ML_simple_array.glm.

Files attached in ZIP:
[ML_Link_Double_Array.zip](https://github.com/gridlab-d/gridlab-d/files/4062142/ML_Link_Double_Array.zip)

Note, normal MATLAB link and runtime compiler pathing will need to be dealt with.
This is also done via a runtime class (all implemented arrays in GLD are either complex_array, or the example file didn't work (e.g., appliance)).

Files run in release/4.2 with MATLAB r2019a on Windows 10 x64.

## Additional notes
If this does get fixed/updated, may want to see if complex_array is possible

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
Native MATLAB support is being deprecated and replaced with HELICS for interacting with MATLAB. HELICS supports full use of sending double arrays. Closing.
