### ISSUE TITLE
Add the 'PV Panel Model' into Solar Class for Inverter Class

### ISSUE THREAD

**Issue by xjasura** [gridlab-d/gridlab-d#1224]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
1) Create a hotfix branch from 'feature730' for adding the 'PV panel model' into the Solar class;
2) The PV panel model solves a nonlinear question that takes the output power as an input, and returns the output voltage; and
3) It involves a function that takes the output voltage for calculating the output current directly.

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by xjasura** [comment]
All relevant changes have been put into feature/730 by Frank.

**Comment by ftuffner** [comment]
No bugs encountered and is part of the v4.3 merge in PR #1256.  Still needs to Wiki updated, but that will occur with the other inverter-related updates (written up in Word, just needs to be put in ShoutWiki).
