### ISSUE TITLE
Unable to build target "dist-deb"

### ISSUE THREAD

**Issue by esilksel** [gridlab-d/gridlab-d#1226]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Attempting to build a deb package via `make dist-deb` fails, complaining of a missing target `dist_dir`.

## Please provide the steps to reproduce.
Checkout the latest develop branch (or on master), run:
```
autoreconf -if
# Sub out the *FLAGS as desired
./configure --prefix=/usr/local/ --enable-silent-rules "CFLAGS= -Ofast -w" "CXXFLAGS=-Ofast -w" "LDFLAGS=-Ofast -w"
make deb-dist
```

## Please provide the exact error/warnining/failure message printed on the console.
On develop:
```
$ make dist-deb
 cd . && /bin/bash /home/ericsilk/Documents/HELICS_Project/gridlab-d/build-aux/missing automake-1.15 --foreign Makefile
 cd . && /bin/bash ./config.status Makefile depfiles
config.status: creating Makefile
config.status: executing depfiles commands
make: *** No rule to make target 'dist_dir', needed by 'dist-deb'.  Stop.
```
On master:
```
make: *** No rule to make target 'dist_dir', needed by 'dist-deb'. Stop.
```

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------
Ubuntu 18.04, ultimately hoping to build within a Docker container (and then install in another container).

**Comment by ftuffner** [comment]
@afisher1 @ntenney I'm not sure how the DEB package is actually build for release.  Is it this command, or is another one used?  I've had to modify `dist-deb` in the past to get around Xerces issues, but I wasn't sure if we were still using it.

**Comment by ftuffner** [comment]
For prior version of GLD.  Current distribution built differently, and may get changed per cmake updates.
