### ISSUE TITLE
Double convert does not detect erroneous player input

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1238]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

The player input in https://github.com/gridlab-d/gridlab-d/blob/master/reliability/autotest/fault_bus_B_within.player has an erroneous entry on line 10 that is not detected by the `convert_to_double() function`.

## Please provide the steps to reproduce.

Run `reliability/autotest/test_fault_current_4_node.glm`. No error is produced when it should produce an error.

## Please provide the exact error/warnining/failure message printed on the console.

None.

## If possible, please provide any screenshots and other supporting information.

Recommend changing `convert_to_double` so it only parses units when the property has units, and if it finds anything after the double value, it reject that unless it can be converted to a compatible unit.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@dchassin An initial fix for the ticketed issue is now up in the bugfix/1238 repository.

However, it raises the broader question on things like this - should an error like this be "non-blocking" in players?  I feel like it shouldn't (should be blocking), but I'm going to get some opinions.  So this should effectively "fix the ticketed issue", but more fixes (or separate tickets) may be created for the overall player behavior.

**Comment by dchassin** [comment]
@ftuffner, I agree that it should be blocking.  In HiPAS we made the error blocking and fixed the test model. However, we recognize that this might cause older models to stop working. For HiPAS this isn't a concern. But maybe an interim solution for the broader GridLAB-D community would be to have an `enumeration on_read_error {IGNORE,WARN,FAIL}` property in players that is by default `WARN` for the next release. Then it can be changed to `FAIL` by default in the following release.

**Comment by ftuffner** [comment]
@dchassin I'll float the idea out to the larger group.  I'm okay with it failing - if the player was having issues before, it would be good for users to see that and know, rather than perpetuating their "bad results".

**Comment by ftuffner** [comment]
@dchassin Understandable.  We have an initial conversion of the tape module to a more C++/standard GLD object-type implementation.  However, it isn't fully working yet (funding redirect), plus there are overall questions on the longevity of even that port.

**Comment by ftuffner** [comment]
Fix for immediate issue merged into /develop.  Closing for now.
