### ISSUE TITLE
FNCS/GridLAB Segfault

### ISSUE THREAD

**Issue by eberleim** [gridlab-d/gridlab-d#1244]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Under certain load conditions when using FNCS, GridLAB-D will segfault and fail silently. 

## Please provide the steps to reproduce.
Contact TESP team.

## Please provide the exact error/warning/failure message printed on the console.
TODO: populate this section @d3j331

**Comment by ftuffner** [comment]
Fix manually pulled into one of the feature/1173 branches, which was pulled into /develop as part of the v4.3 process.  Closing.
