### ISSUE TITLE
Incorrect documentation for the units of ‘design_internal_gains’

### ISSUE THREAD

**Issue by Hayden-Reeve** [gridlab-d/gridlab-d#1248]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ ] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

1.	The source code and wiki list the units as [W/sf]. This seems to be incorrect and likely a cut and paste error from the now deprecated ‘design_internal_gain_density’.
a.	http://gridlab-d.shoutwiki.com/wiki/Design_internal_gains
b.	https://github.com/gridlab-d/gridlab-d/blob/f56223aa6e10dd130668ec9f8092da96f5d3f895/residential/house_e.cpp#L266
2.	The residential module wiki lists the correct units [BTU/hr] base on inspection of the default values. However it later gives an equation [(Design sensible cooling load (Btu/hr) = UA * (Design outdoor temperature cooling - Design indoor temperature cooling) + Design internal gains * 3.413 (Btu/hr-kW) + Design solar_radiation * Ag * SHGC * WET)] that suggests the units should be kW or W depending on whether you believe the units or the conversion factor.
a.	http://gridlab-d.shoutwiki.com/wiki/Residential_module_user%27s_guide#Design_Loads_and_HVAC_System_Sizing

I would recommend these changes:
1.	Correct the units in the design_internal_gains wiki and source code to BTU/hr
2.	Remove “* 3.413 (Btu/hr-kW)” from the residential module wiki equation
3.	Create hyperlinks in the house and design_internal_gains wiki pages to the residential module page. There is connectivity between these.  It is quite easy when doing a google search on the house object to not find the residential module documentation.  Explicit links would help this.

## Please provide the steps to reproduce.
N/A - not execution related

## Please provide the exact error/warning/failure message printed on the console.
N/A - not execution related

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
I have redefined the default parameters to be BTU/h in the source code and documentation. closing the issue.
