### ISSUE TITLE
why my output file does not match up with the timestamp?

### ISSUE THREAD

**Issue by duyanran** [gridlab-d/gridlab-d#1252]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [√ ] I have not found an open issue describing the same problem.
- [√ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ √] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

i try to get current info from a IEEE-13 nodes file, but the timestamp just didnt match and the output record didnt follow with what i wish it to be, its a bit hard for me to describe it, so i post the relevant codes here. i am new to this software, really need some help， thanks！

//--------------- this is my clock info ---------------------
clock {
	timestamp '2014-01-01 0:00:00';
	starttime '2014-01-01 0:00:00';
	stoptime '2014-01-07 0:01:30';
	timezone EST+5EDT;
}

//------------------normal ieee-13 set up--------------------------
//。。。。。。。。。。。。。。。。。。。。。。。
//-------------------after all normal set up--------------------------
 //---------------------to record currents------------------------------
object group_recorder {
    name recorder_1;
    group "class=overhead_line";
    file current_in_A.csv;
    interval 600;
    property current_in_A;
    //complex_part REAL;
}
object group_recorder {
    name recorder_2;
    group "class=overhead_line";
    file current_in_B.csv;
    interval 600;
    property current_in_B;
    //complex_part REAL;
}
object group_recorder {
    name recorder_3;
    group "class=overhead_line";
    file current_in_C.csv;
    interval 600;
    property current_in_C;
    //complex_part REAL;
}

object group_recorder {
    name recorder_4;
    group "class=underground_line";
    file current_in_A_un.csv;
    interval 600;
    property current_in_A;
    //complex_part REAL;
}
object group_recorder {
    name recorder_5;
    group "class=underground_line";
    file current_in_B_un.csv;
    interval 600;
    property current_in_B;
    //complex_part REAL;
}
object group_recorder {
    name recorder_6;
    group "class=underground_line";
    file current_in_C_un.csv;
    interval 600;
    property current_in_C;
    //complex_part REAL;
}

//--------------- to record voltages ---------------------

object group_recorder {
    name rec_v_1;
    group "class=node";
    file voltage_A.csv;
    interval 600;
    property voltage_A;
    //complex_part REAL;
}
object group_recorder {
    name rec_v_2;
    group "class=node";
    file voltage_B.csv;
    interval 600;
    property voltage_B;
    //complex_part REAL;
}
object group_recorder {
    name rec_v_3;
    group "class=node";
    file voltage_C.csv;
    interval 600;
    property voltage_C;
    //complex_part REAL;
}

object group_recorder {
    name rec_v_4;
    group "class=load";
    file voltage_l_A.csv;
    interval 600;
    property voltage_A;
    //complex_part REAL;
}
object group_recorder {
    name rec_v_5;
    group "class=load";
    file voltage_l_B.csv;
    interval 600;
    property voltage_B;
    //complex_part REAL;
}
object group_recorder {
    name rec_v_6;
    group "class=load";
    file voltage_l_C.csv;
    interval 600;
    property voltage_C;
    //complex_part REAL;
}

-------------------------------------------------------------------------------------------------------------
this is my output 
![image](https://user-images.githubusercontent.com/56710672/87816122-63e93200-c899-11ea-93fc-7affba7d19ad.png)
this is the demo player output file(watch out the timestamp)
![image](https://user-images.githubusercontent.com/56710672/87816242-9c890b80-c899-11ea-9c16-1cadd00cc794.png)

did i do something wrong ？by the way i dont know how to add meter to measure current and voltage conveniently. really need some guidance or related link. sorry to bother.

**Comment by jcfuller1** [comment]
duyanran,

This question will probably get a better response on the user forum.  I have re-posted it here:  https://sourceforge.net/p/gridlab-d/discussion/842562/thread/fe87d1dd61/

**Comment by duyanran** [comment]
> duyanran,
> 
> This question will probably get a better response on the user forum. I have re-posted it here: https://sourceforge.net/p/gridlab-d/discussion/842562/thread/fe87d1dd61/

thanks for your reminder！i‘ll post it there next time

**Comment by duyanran** [comment]
> duyanran,
> 
> This question will probably get a better response on the user forum. I have re-posted it here: https://sourceforge.net/p/gridlab-d/discussion/842562/thread/fe87d1dd61/

hi, i cant find the post button on user forum(could you give me a photo or shortcut of the page? thanks a lot!!
