### ISSUE TITLE
Helics : Cannot return the current time or less than the current time

### ISSUE THREAD

**Issue by Seragonia** [gridlab-d/gridlab-d#1253]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
When using a Helics period < 1, GridLab-D outputs the error "Cannot return the current time or less than the current time". This error is already described here: [See Sourceforge forum](https://sourceforge.net/p/gridlab-d/discussion/842562/thread/20af81374b/).
However, the proposed solution (using a newer build version of GridLab-D from the develop branch) does not work. The version I use is:
commit 7faf347cb1052845912919c3d36f353a366a1f5a (origin/develop)
Merge: 772d1203 8a3297c3
Author: Laurentiu Marinovici <laurmarinovici@gmail.com>
Date:   Fri Jun 19 13:32:10 2020 -0700

## Please provide the steps to reproduce.
Start a co-simulation including GridLab-D with Helics and specify a period less than 1.

## Please provide the exact error/warnining/failure message printed on the console.
```
ERROR    [2020-01-01 00:00:00 EST] : helics_msg::clock_update: Cannot return the current time or less than the current time.
ERROR    [2020-01-01 00:00:00 EST] : exec halted: clock time is negative (global_clock=-1)
FATAL    [2020-01-01 00:00:00 EST] : shutdown after simulation stopped prematurely
FATAL    [2020-01-01 00:00:00 EST] : environment startup failed: Success
```

## If possible, please provide any screenshots and other supporting information.
Example of configuration:
```json
{
   "name": "config_helics",
   "period": 0.75,
...
```

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
are you using running a subsecond (deltamode) model in GridLAB-D? If not you can't have a period less than 1 second in the federate configuration.

**Comment by afisher1** [comment]
No reply on this one since my original question. When running in deltamode the period is set to the deltamode timestep. The user should never set the period to less than one in the configuration file. Closing due to user error.
