### ISSUE TITLE
Using "group" for MySQL recorder and regulator causes segmentation fault

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1268]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
[MySQL recorders](http://gridlab-d.shoutwiki.com/wiki/Recorder_(mysql)) allow us to record output from multiple objects by group. I've successfully used this with triplex meters like so:

```
...

object triplex_meter {
	phases AS;
	name tpm0_R2-12-47-2_tm_1_R2-12-47-2_tn_193;
	parent R2-12-47-2_tm_1;
	measured_stats_interval 900;
	nominal_voltage 120;
	groupid AMI_group;
};

object mysql.recorder {
    name secondary_recorder;
	property measured_avg_real_power_in_interval, measured_avg_reactive_power_in_interval, measured_avg_voltage_12_mag_in_interval;
	interval 900;
	group "groupid=AMI_group";
	table secondary;
	query_buffer_limit 20000;
	limit -1;
	mode w;
	header_fieldnames "name";
};

...
```

However, attempting to use "group" with a voltage regulator results in a segmentation fault (details below).

## Please provide the steps to reproduce.
- Build GridLAB-D from source (`develop` branch at `c91d58480b1ff959714a4e874ef9c734ff9e27a3`) with MySQL connectivity on Debian Buster.
- Run the following model (it should succeed, but you'll likely need to update the `database` object):
```
// Simple model with two nodes and a voltage regulator. Taps change via tape
// players.

clock {
	starttime '2018-01-01 00:00:00';
	stoptime '2018-01-01 00:02:30';
}

module powerflow {
    solver_method NR;
    line_limits FALSE;
    line_capacitance FALSE;
}

module tape;
module mysql;

object database {
   // Update to "localhost" for local MySQL installation.
   hostname "db";
   username "gridlabd";
   password "gridlabd";
   schema "gridlabd";
   port 3306;
   tz_offset 0;
}

// Nodes up and down stream of voltage regulator.
object meter {
  name "vreg_node_upstream";
  phases ABCN;
  nominal_voltage 7200;
  bustype SWING;
}
object node {
  name "vreg_node_downstream";
  phases ABCN;
  nominal_voltage 7200;
}

object regulator_configuration {
  name "vreg_conf";
  connect_type WYE_WYE;
  // Taps will be altered via player files.
  Control MANUAL;
  // Since we're manualy controlling this regulator and just want to get quick
  // changes, ensure we use small delays.
  dwell_time 0.1;
  time_delay 0.1;
  // Taps can be changed individually.
  control_level INDIVIDUAL;
  raise_taps 16;
  lower_taps 16;
  regulation 0.1;
  Type B;
  // Put taps at 0 to start. The players will take care of the rest.
  tap_pos_A 0;
  tap_pos_B 0;
  tap_pos_C 0;
}

object regulator {
  name "vreg";
  from "vreg_node_upstream";
  to "vreg_node_downstream";
  phases ABC;
  configuration "vreg_conf";
  // Assign to a group.
  groupid regulator_group;
}

// Use players to tap regulators.
object player {
    name tap_player_A;
    parent vreg;
    property tap_A;
    file tap_position.player;
    loop 100;
}
object player {
    name tap_player_B;
    parent vreg;
    property tap_B;
    file tap_position.player;
    loop 100;
}
object player {
    name tap_player_C;
    parent vreg;
    property tap_C;
    file tap_position.player;
    loop 100;
}

// MySQL recorder for taps.
object mysql.recorder {
    name regulator_recorder;
	property tap_A, tap_B, tap_C, tap_A_change_count, tap_B_change_count, tap_C_change_count;
	interval 60;
    // Using the "parent" approach works.
	parent vreg;
    // Using the group approach causes a Segmentation fault.
    // group "groupid=regulator_group";
	table regulators;
	query_buffer_limit 20000;
	limit -1;
	mode w;
	header_fieldnames "name";
};
```
Here's the associated `tap_position.player` file:
```
2018-01-01 00:00:00, 16,
+60s, 15,
+60s, 14,
```
- After running, you can observe the tap positions in the `gridlabd` database, `regulators` table.
- After successfully running, modify the `mysql.recorder` object. Specifically, comment out the `parent vreg;` line and uncomment the `group "groupid=regulator_group";` line.
- Save the modified model.
- Run the modified model. Segmentation fault ensues.

## Please provide the exact error/warnining/failure message printed on the console.
```
root@149a3851e2a2:/models# gridlabd recorder_issue.glm
WARNING  [INIT] : The external solver solver_KLU could not be found, defaulting to superLU
Segmentation fault
```

## If possible, please provide any screenshots and other supporting information.
- GridLAB-D version: 
```
root@149a3851e2a2:/models# gridlabd --version
GridLAB-D 4.3.0-18551 (Navajo [c91d5848:develop:Mod]) 64-bit LINUX RELEASE
```
- MySQL version:
```
root@4a12e2862b23:/# mysqld --version
/usr/sbin/mysqld  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)
```
- MySQL connector installed like so prior to building+installing GridLAB-D:
```
apt-get update && apt-get install -y wget && \
    # These first two packages (mysql-common and
    # mysql-community-client-plugins) are prerequisites for libmysqlclient
    # (and by extension, libmysqlclient-dev).
    wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-common_8.0.22-1debian10_amd64.deb && \
    wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-community-client-plugins_8.0.22-1debian10_amd64.deb && \
    wget https://dev.mysql.com/get/Downloads/MySQL-8.0/libmysqlclient21_8.0.22-1debian10_amd64.deb && \
    wget https://dev.mysql.com/get/Downloads/MySQL-8.0/libmysqlclient-dev_8.0.22-1debian10_amd64.deb && \
    # Install.
    apt install -y ./*.deb
```

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@blthayer I can confirm I see the same behavior on my end.  I'll see if I can track down where it is broken.

**Comment by ftuffner** [comment]
@blthayer I've pushed a fix up to issue/1268 that appears to fix the issue.  If you have a chance, please pull it and give it a test.

**Comment by blthayer** [comment]
@ftuffner - as per usual responsive and helpful! Thank you!

I've pulled down and built `issue/1268`, and can confirm that my example now works with `group` for regulators.

**Comment by ftuffner** [comment]
@blthayer Glad to hear it worked.  I'll set the pull request to get this into the mainline branch and hopefully into v4.3.
