### ISSUE TITLE
Augment meter min/max/avg capabilities to track per-phase power

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1270]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Three-phase meters are capable of tracking min/max/avg power over a given interval, but currently this is only implemented for 3-phase power. I'll be submitting a pull request shortly that augments this capability to also track min/max/avg for each individual phase.

## Please provide the steps to reproduce.
N/A

## Please provide the exact error/warnining/failure message printed on the console.
N/A

## If possible, please provide any screenshots and other supporting information.
N/A

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Merge complete.  Closing issue.
