### ISSUE TITLE
measured_avg_voltage_<phase>_in_interval quantities always read 0

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1272]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
When using a meter to record `measured_avg_voltage_<phase>_in_interval` quantities, they all come back as 0.

## Please provide the steps to reproduce.
Create a model with a meter and a recorder. Configure the recorder to record `measured_avg_voltage_A_in_interval` and note all quantities come back as 0.

## Please provide the exact error/warnining/failure message printed on the console.
N/A

## If possible, please provide any screenshots and other supporting information.
In meter.cpp, it can be seen that the aforementioned fields/variables are initialized to `0.0`, but never updated, despite the values being calculated like:
```C++
last_measured_avg_voltage_mag[0] = ((interval_dt * last_measured_avg_voltage_mag[0]) + (dt * last_measured_voltage[0].Mag()))/(interval_dt + dt);
```

As far as I can tell from my preliminary digging (no code has been run, so more may be necessary), one just needs to add the following lines in `meter.cpp`:
```C++
measured_avg_voltage_mag_in_interval[0] = last_measured_avg_voltage_mag[0];
measured_avg_voltage_mag_in_interval[1] = last_measured_avg_voltage_mag[1];
measured_avg_voltage_mag_in_interval[2] = last_measured_avg_voltage_mag[2];
measured_avg_voltageD_mag_in_interval[0] = last_measured_avg_voltageD_mag[0];
measured_avg_voltageD_mag_in_interval[1] = last_measured_avg_voltageD_mag[1];
measured_avg_voltageD_mag_in_interval[2] = last_measured_avg_voltageD_mag[2];
```

I'll plan on submitting a PR shortly.
-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@blthayer As a quick question, make sure you have the `measured_stats_interval` field with a valid value.  The min/max/average code bogs down meter a bit, so we use that as a flag - if you don't set it, those values don't get calculated.

**Comment by blthayer** [comment]
@ftuffner thanks for pointing that out. In this case, I definitely did have the `measured_stats_interval` defined: the problem surfaced when I was getting valid average power readings but 0's for voltage averages. I got sidetracked by some other work, but with some luck I'll have a PR with new autotests sent your way in a couple hours.

**Comment by blthayer** [comment]
@ftuffner - any chance you can spare a few minutes to help me figure out why my tests are (partially) failing?

In short, I have a simple test set up:
- swing node only, nothing else in the system
- voltages played in each minute for 1 hour
- 15 minute averages (stats interval)
- expected results contained in .csv files
- I included the Python script that generated players + .csvs for reference, though you shouldn't need to use this script and should be able to work directly with the files.

Summary of voltage average results:
- Correct for minutes 0 through 14
- Incorrect for minutes 15 through 29
- Correct for minutes 30 through 44
- Correct for minutes 45 through 59
- Correct for minute 60 (I have the clock running one extra minute to ensure this average gets computed)

This leads me to believe that either there's a bug in `meter.cpp` related to the first stats initialization or that my test is incorrect due to a lack of understanding on my end of the expected initialization behavior. I couldn't find anything wrong with `meter.cpp`, though I don't have an actual dev environment set up.

I did a fair bit of experimenting to try to figure out what values may have been used to compute the incorrect values, but never did figure it out.

Details to get set up:
- Clone from https://github.com/utilidata/gridlab-d-fork/tree/issue/1272
- Build (of course)
- Create temporary subdirectory in `powerflow/autotest` and work from it
- Run `gridlabd ../test_ami_average_voltage_features_NR.glm`
- Player files are named `data_voltage_values_AMI_average_test_<phase>.player`
- Expected results stored in .csv files named `data_AMI_average_test_15_min_avg_voltage_mag_<phase>.csv`
- The test model has a pair of recorders commented out that one can use for debugging after commenting out all the assert blocks.

**Comment by blthayer** [comment]
@ftuffner - please ignore my previous comment in this thread, I was able to figure out what the problem was.

**Comment by ftuffner** [comment]
@blthayer I'm a bit late getting back to this.  I'll assume the PR is still valid and needs to be examined though, correct?

**Comment by blthayer** [comment]
@ftuffner No worries! Correct - the PR is still valid and needs a review + merge (if found satisfactory, of course). This issue can be closed after the PR is closed.

**Comment by ftuffner** [comment]
PR merged in successfully - closing this.
