### ISSUE TITLE
impedance dump documentation/clarification

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1276]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
The `powerflow`'s `impedance_dump` object appears to be maintained but is undocumented (no mention in the wiki, nearly 0 code comments in `impedance_dump.cpp` or `impedance_dump.h`).

## Please provide the steps to reproduce.
N/A

## Please provide the exact error/warnining/failure message printed on the console.
N/A

## If possible, please provide any screenshots and other supporting information.
The impedance dump functionality seems incredibly useful for any users who need data beyond powerflow results. Unfortunately, it's left to the user to figure out how the output should be interpreted. 

I have a copy of **Distribution System Modeling and Analysis** by William Kersting (3rd edition), and as far as I can tell, the impedance dump output corresponds to the [*a*], [*b*], [*c*], [*d*], [*A*], and [*B*] matrices introduced in chapter 6.1 (I'll be doing some lightweight validation/testing to confirm - for instance [*a*] and [*d*] should be identical, `[A] = [a]^-1`, `[B] = [a]^-1[b]`). However, the lack of documentation means any caveats or "gotchas" will remain unknown.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Added a [wiki page](http://gridlab-d.shoutwiki.com/wiki/Impedance_dump)  with some sparse details. Impedance dump is mostly meant as a diagnostic object, so there may be caveats/"gotchas" we haven't found yet.

**Comment by blthayer** [comment]
@ftuffner Thank you, this was very helpful! You are appreciated!
