### ISSUE TITLE
Cannot extract power flow results from XML file

### ISSUE THREAD

**Issue by mamuniut09** [gridlab-d/gridlab-d#1278]
Hello everyone,

I am very new to gridlab-d. I have a IEEE_4_node.glm file. In the GridLAB-d console I write the below command to run the power flow,
gridlabd IEEE_4_node.glm
Then, I write the following command to save the results in xml file.
gridlabd IEEE_4_node.glm -o results.xml
However, I cannot open the results.xml file to see the power flow results. Now, I have the below questions.

1. Is this the proper way of running the power flow and, then, save the results?
2. How can I open the xml file and extract data from it for future analysis?

The gml and xml files are in the attached zip file below.

[IEEE4Node.zip](https://github.com/gridlab-d/gridlab-d/files/5736511/IEEE4Node.zip)

Thank you,
Mamun

**Comment by ftuffner** [comment]
@mamuniut09 I guess I'm a little confused on the questions here.  Your attached file seems fine to me, as does the base GLM.  It is an XML-formatted file, so "human readable" is debatable - you'd have to find the appropriate fields and extract them.

If you are trying to get the "pretty web-page output", you need to update the style file.  We don't have one properly generated for the new versions of GridLAB-D at the moment, but you can create a local copy.  To do this, just run the command:

	gridlabd --xsl powerflow

which will generate an XSL file (in my case, it generated `gridlabd-4_3.xsl`).  Note that you have to add other modules to the list if you want the style sheet for others (e.g., residential, market, etc.).  With this generated, change the `stylesheet` in your GLM (line 12) to be the file without the XSL extension.  e.g., for me, it was:

	#define stylesheet=gridlabd-4_3

Run GridLAB-D again with the output specified.  Now your XML has an associated XSL and "looks pretty" in a web browser.

Depending on what you are trying to extract, there may be "better options".  If you are only interested in the voltage and current for the powerflow solution, you should look into the `voltdump` and `currdump` objects.  See http://gridlab-d.shoutwiki.com/wiki/Power_Flow_User_Guide#Volt_Dump and http://gridlab-d.shoutwiki.com/wiki/Power_Flow_User_Guide#Current_Dump for more details.

**Comment by ftuffner** [comment]
No response/activity for three months - assuming resolved.
