### ISSUE TITLE
Integrate HELICS 3.0 

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1279]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [ ] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ ] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
branch feature/1279 currently supports the latest v3.0.0-alpha.2 tag of HELICS

**Comment by afisher1** [comment]
This branch will be constantly updated to work with HELICS 3.0 alpha and beta releases until the stable 3.0 release of HELICS is released.

**Comment by blthayer** [comment]
@afisher1 - I saw some activity on the feature branch for the HELICS 3 update a week or two ago. What's the state of HELICS 3 integration in GridLAB-D? Is it more or less complete?

**Comment by afisher1** [comment]
@blthayer - Yes sorry I missed this I've been out sick with Covid basically since the beginning of september. I'm back and recovered now. This works branch works with 3.0.0. I'm testing with 3.1.0 as I speak. it is also possibly missing some updates from the develop branch for some of the GridAPPS-D application needs. But from a HELICS 3.0 standpoint its fully functional.

**Comment by j-pennington** [comment]
@afisher1 Thanks for your important work on HELICS integration.  Have there been any recent updates on this effort?

**Comment by StormsHalted** [comment]
@afisher1 @j-pennington 

Have you released a working version of Helics 3.0 with the current gridlab-D version? if yes where can I see the instructions to build the integration?

**Comment by afisher1** [comment]
This is currently in the develop branch. Please see http://gridlab-d.shoutwiki.com/wiki/CMake_Build. Our next release we are switching to cmake for our source build. the develop branch is built using CMake.
