### ISSUE TITLE
Power Curves and Generic wind turbines

### ISSUE THREAD

**Issue by BilalAhmad-Bhatti** [gridlab-d/gridlab-d#1284]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------
Commercial wind turbine performance is documented using a power curve that relates electric power to wind speed at hub height. It is more reasonable to expect a user to provide a power curve than the generator and Coefficient of performance specifications. Furthermore, a set of generic turbines and a normalized generic power curve have been developed at PNNL. 
This functionality could be built into the wind turbine implementation of GridLAB-D.

**Comment by ftuffner** [comment]
Merged in as part of v4.3 updates - closing
