### ISSUE TITLE
Version 5.0 - Remove DEPRECATED properties prior to RC

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1288]
## Please describe what was the cause of the issue?
Find all PT_DEPRECATED properties from v4.3 and remove them prior to v5.0 roll-out.  May want to do early, so users get accustomed to them being missing.

## Please provide the steps to reproduce.
Find PT_DEPRECATED flags in published properties.

-------------------------------------------------------------------------------------------------------------

**Comment by trevorhardy** [comment]
Deprecated properties removed and all autotests passing.
