### ISSUE TITLE
Unit conversion bug with HELICS integration

### ISSUE THREAD

**Issue by blthayer** [gridlab-d/gridlab-d#1302]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
When using a federate in a HELICS federation to control a GridLAB-D model's inverter `Q_Out` property with endpoint units set to `VAr`, an error occurs.

## Please provide the steps to reproduce.
Steps to reproduce are detailed in the [gridlab-d-helics-bug-reproduction](https://github.com/utilidata/gridlab-d-helics-bug-reproduction) repository, **specifically in the [units-bug](https://github.com/utilidata/gridlab-d-helics-bug-reproduction/tree/units-bug) branch.**

For completeness, a .zip archive of repository at the correct branch has been attached to this ticket.

## Please provide the exact error/warnining/failure message printed on the console.
More details can be found in the aforementioned repository.
```
gridlab-d        | ERROR    [2018-01-01 00:00:00 UTC] : unit_find(char *unit='<▒U'): unitfile.txt(202): unable to find or derive unit '<▒U'
gridlab-d        | ERROR    [2018-01-01 00:00:00 UTC] : could not find unit '<▒U'
gridlab-d        | ERROR    [2018-01-01 00:00:00 UTC] : could not run unit_convert_ex due to null arguement
gridlab-d        | ERROR    [2018-01-01 00:00:00 UTC] : convert_to_double(const char *buffer='16<▒U', void *data=0x0x558ee63a8a20, PROPERTY *prop={name='Q_Out',...}): unit conversion failed

```

## If possible, please provide any screenshots and other supporting information.
See attached .zip file or linked repository.

-------------------------------------------------------------------------------------------------------------
[gridlab-d-helics-bug-reproduction-units-bug.zip](https://github.com/gridlab-d/gridlab-d/files/6671927/gridlab-d-helics-bug-reproduction-units-bug.zip)

**Comment by afisher1** [comment]
This is a co-simulation implementation issue. I don't believe endpoints were designed to handle unit information correctly like publications. If you remove the unit info from the endpoints and make sure when creating the message add a space between the value and unit. I should work then.
