### ISSUE TITLE
"Harmonize" the use of status in link-based powerflow objects, so it works properly with reliability/reconfiguration

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1307]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
At present, the "status" variable in link-based powerflow objects is largely ignored, except for switch-based devices and fuses.  This should probably behave consistently for all of the link-based objects and allow sections to be switched out (without a switch) that way.

## Please provide the steps to reproduce.
Modify the "status" variable to "OPEN" for any link-based object, not just switches or fuses.  Chances are it won't actually do anything, other than possibly mess up the initial admittance/impedance calculation.

## Please provide the exact error/warning/failure message printed on the console.
N/A

## If possible, please provide any screenshots and other supporting information.
N/A

-------------------------------------------------------------------------------------------------------------

**Comment by trevorhardy** [comment]
@ftuffner, this can be closed out with the work on #1307, right?
