### ISSUE TITLE
not being able to Link GRIDLAB-D with MATLAB with error object not found

### ISSUE THREAD

**Issue by NasirAbbas514** [gridlab-d/gridlab-d#1309]
I am trying to link Gridlab d with matlab but still not being able to remove this error even after multiple events.
the error is

ERROR    [INIT] : link_initall(target='matlab'): object 'meter2  ' is not found

I am attaching screenshot for a better understanding of the problem
![Screenshot (40)](https://user-images.githubusercontent.com/76805743/132468482-c3be74af-1144-48b9-8521-9f9f264ef101.png)

**Comment by NasirAbbas514** [comment]
thanks that error got removed but still having another error.

ERROR    [INIT] : aggregate group '' is not valid

**Comment by ftuffner** [comment]
I'm not able to replicate that error.  I tried your code with GridLAB-D v4.3RC and MATLAB 2020b and MATLAB 2015a without any issues.  What version of GridLAB-D are you using (`gridlabd --version`) and how did you "obtain it" (downloaded, built from scratch, a combination thereof)?

**Comment by ftuffner** [comment]
No updates in 30 days - assuming resolved/answered - closing
