### ISSUE TITLE
Tape player sscanf typecast for raw timestamps is incorrect

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1311]
https://github.com/gridlab-d/gridlab-d/blob/46541cb8babdd34e371c42467c3830f03f73b96c/tape/player.c#L429

The value should be cast to a `TIMESTAMP` not a `unsigned short`.  The current cast results in erroneous date/time values.

**Comment by d3j331** [comment]
Close issue, with commit
