### ISSUE TITLE
Update taxonomy feeder files for triplex_load devices

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1315]
## Please describe what was the cause of the issue?
With the deprecation of `power_12` in triplex_node/triplex_meter objects (to encourage users to use the triplex_load object), the various taxonomy feeder GLMs should probably be updated to "reflect proper practice".

**Comment by ftuffner** [comment]
Should probably update both the Tools repository version and the autotests.  Unsure what we want to do with the MATLAB population scripts at that point, since this will likely break them

**Comment by temcdrm** [comment]
In using "extra" triplex_load objects, are there any implications with respect to 1) limits on grandchildren connected to a triplex_node or triplex_meter, or 2) additional runtime due to having more objects in the model?

**Comment by trevorhardy** [comment]
@ftuffner TESP has its own population script that will need to be updated as well. I don't know if PNNL should consider the TESP script canonical but I suspect it is the one that is getting the most TLC at the moment.

**Comment by temcdrm** [comment]
GridAPPS-D and CIMHub may also be affected.  They write triplex loads and circuits onto a feeder backbone, and we had to tweak this because of the grandchild restriction.  The feeder backbones would probably still work, but if there are deprecated attributes, there could be lots of new warnings.

**Comment by dchassin** [comment]
Is it ok to simply replace`triplex_node` with `triplex_load` in any affected models?  That's what we've been doing on the National Grid models converted from CYME.

**Comment by ftuffner** [comment]
@temcdrm My initial plan was to just do a blanket replacement as @dchassin states, then update the properties.  Theoretically, this is just doing a couple find/replace sets on each file.  This wouldn't add any new objects (so the grandchild problem won't be an issue), and performance impact should be nonexistent/negligible (I guess technically triplex_load would do some more init stuff, since it is a subclass of triplex_node).  If we wanted to be "more clever", the triplex_node objects without a power_X value could just be left, as-is in the files.  Theoretically, with this replacement approach, script updates would just be "look for constant_power_X in triplex_load" instead of "look for power_X in triplex_node".  I don't expect any topology/structure changes overall, so it shouldn't break the mechanisms of the scripts (at least reading the taxonomy feeders).

The other debate/question I have here is if we want to get rid of the old colon notation in the base files.  Out side of the line/transformer configurations, it is not used (all nodes have proper names and are referenced as such, at least on first glance).  I'm pretty sure the GridAPPS-D/TESP scripts are smart enough to not fail if it is missing, but I know the old MATLAB script expects them.  That said, the MATLAB scripts may have other issues (they are from the SGIG analysis 10 years or so ago), so we may just archive them with an "unaltered set of GLMs" - just dump it into a ZIP file or something.  I typically point everyone to one of the Python ones (might be the TESP ones @trevorhardy mentioned) for any uses anymore, mostly because the MATLAB ones are very poorly written and extremely hard to add to/debug (lots of jj, jjjj, jjjjj type variables).

**Comment by D3k205** [comment]
glm files are updated
pull request has been generated
pull request name is feature/1315

**Comment by ftuffner** [comment]
Description was a little vague, so initial attempt was too much of a find/replace (needs to be more nuanced).

`triplex_node` and `triplex_meter` objects with load values (`power_X`,`current_X`, `impedance_X`,etc.) should be replaced with a `triplex_load` and the load fields by the `constant_X` equivalent (e.g., `power_1` becomes `constant_power_1`)
