### ISSUE TITLE
issue in using server mode of gridlabd

### ISSUE THREAD

**Issue by karuneshm95** [gridlab-d/gridlab-d#1317]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
i searched for tutorial for using gridlabd in server mode but I don't able to understand it clearly . If possible , please provide with example for building in server mode

## Please provide the steps to reproduce.
steps for using gridlab d in server mode with working example and commands

## Please provide the exact error/warnining/failure message printed on the console.

 also , direct using in GUI mode

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Semi-copied from #1316:

Server mode doesn't require any special build steps.  Compiling GridLAB-D "normally" or installing from a precompiled version will both include server mode.

Regarding server mode examples/usage, the documentation is at http://gridlab-d.shoutwiki.com/wiki/Realtime_server. It is a largely unused, and nearly deprecated mode. Depending on what you are trying to do, using the HELICS cosimulation framework may be a better option.

**Comment by ftuffner** [comment]
No updates in 30 days - assuming resolved/answered - closing
