### ISSUE TITLE
Implement fixed-point current-injection powerflow solver

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1319]
Implement the fixed-point current-injection-based powerflow solver to enable GridLAB-D better stability for fault and "difficult system" solutions.

**Comment by trevorhardy** [comment]
I mis-read this and thought that you had already implemented it and I was so very excited. Now I'm just a little excited knowing that it might get done soon-iso.

**Comment by dchassin** [comment]
This one gets a big thumbs-up from the SLAC team.

**Comment by afisher1** [comment]
has been merged into develop. closing.
