### ISSUE TITLE
MATLAB_link - Add check for semi-colon on "non-needed" properties to help debug

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1328]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
If `import` or `export` lines in the matlab_link functionality end in a semi-colon, they are basically ignored.  No error is produced, but nothing happens in the simulation either.

## Please provide the steps to reproduce.
Take a working MATLAB link example and put a semi-colon on the end.  See attached as a "failing case" (from forum post on SourceForge).
[mlink_semicolon_issue.zip](https://github.com/gridlab-d/gridlab-d/files/8234320/mlink_semicolon_issue.zip)

**Comment by dchassin** [comment]
These are supposed to call the corresponding module's import/export functions. The absence of the required module function should definitely result in an error. Most modules do not implement these. I believe the only one that still uses it is `mysql`, which read and writes a GLM model from/to a MySQL database.  I don't know how much it's being used.

**Comment by dchassin** [comment]
I've noticed that some name resolution functions fail when dots are present.

**Comment by dchassin** [comment]
Seems like `gldcore/link.cpp:308` may need to include a semicolon as the line terminator, e.g., `if ( sscanf(line,"%s %[^\r\n;]",tag,data)>0 )`

**Comment by dchassin** [comment]
An `else` block with an error/warning on that test may be necessary as well.

**Comment by afisher1** [comment]
Since the matlab link support is being deprecated for HELICS interface this is no longer necessary to fix. closing.
