### ISSUE TITLE
Wind Speed Specification for Wind Turbines | TAP-API Integration

### ISSUE THREAD

**Issue by BilalAhmad-Bhatti** [gridlab-d/gridlab-d#1330]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

For the existing wind turbine implementation, the wind speed is specified through the climate object. In the absence of the climate object, it defaults to a fixed value. This enhancement would enable the users to specify the wind speed time series data through a .player file. 
Thus, enabling the users to use wind speed data generated by Distributed Wind Tools Assessing Performance (TAP) API or other sources. 

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Code merged in.  Closing issue.
