### ISSUE TITLE
Typo in house_e source code for cooling COP units

### ISSUE THREAD

**Issue by carolyngoodman1** [gridlab-d/gridlab-d#1337]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
https://github.com/gridlab-d/gridlab-d/blob/master/residential/house_e.cpp#L324
http://gridlab-d.shoutwiki.com/wiki/Residential_module_user%27s_guide#HVAC_and_Electrical_Loads
On line 324 of the house-e module, the units for cooling COP are listed as "Btu/kWh". After looking through the source code and the documentation, it seems the cooling COP units should be listed as "pu" like the heating COP one line above. 

## Please provide the steps to reproduce.
Look at source code line where cooling_cop is defined.

## Please provide the exact error/warnining/failure message printed on the console.
No error. Just a typo in the comment.

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
just pushed a fix to develop for this issue.
