### ISSUE TITLE
Deprecate MATLAB-link support

### ISSUE THREAD

**Issue by trevorhardy** [gridlab-d/gridlab-d#1351]
With the full support of HELICS and the use of a soon-to-be-deprecated feature in MATLAB that allows the direct connection between GridLAB-D and MATLAB, let's officially deprecate the MATLAB-link feature and point users towards HELICS.

**Comment by afisher1** [comment]
@trevorhardy do we have any matlab-gridlabd helics examples to point people to? This would also help I think.

**Comment by trevorhardy** [comment]
Not right now. It is on the to-do list.

**Comment by afisher1** [comment]
closing will create a new ticket to point deprecated maltab-link documentation to helics matlab documentation.
