### ISSUE TITLE
inverter_dyn connected to a childed triplex device is failing to work

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1352]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

When an inverter_dyn is connected to a childed triplex device, it fails indicating it can't find the proper matrix connection.

## Please provide the steps to reproduce.
Connect an inverter_dyn to a childed triplex object in a power system.  Seems to be in GFL, but probably in both GFM and GFL modes.

## Please provide the exact error/warning/failure message printed on the console.
```ERROR    [2001-08-01 13:00:00 PDT] : sync_triplex_meter(obj=8484;sx2897772a_pvmtr): Node:8484 - sx2897772a_pvmtr - Failed to map deltamode matrix to parent```

## If possible, please provide any screenshots and other supporting information.
N/A

-------------------------------------------------------------------------------------------------------------

**Comment by afisher1** [comment]
merged into develop. closing
