### ISSUE TITLE
Wind Turbine-Inverter Coupling | Enabling Smart Inverter Functions for Wind Turbine

### ISSUE THREAD

**Issue by BilalAhmad-Bhatti** [gridlab-d/gridlab-d#1364]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

This enhancement enables wind turbine coupling with the inverter parent. The coupling bypasses the converter stage in the inverter object since that is assumed to be handled inside the wind turbine object. 
As a result of this enhancement, the wind turbine object can access the smart inverter functionality built in the inverter object.

**Comment by ftuffner** [comment]
Code merged into develop
