### ISSUE TITLE
Evaluate if Xerces support still needed - remove if not

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1367]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
As part of the v5.0 build update/release, evaluate if the Xerces library is still used and if the functionality even works.  It appears to only be part of the loader (`gldcore/load.c` and then `load_xml_handle.cpp` and `load_xml.cpp`).

The "XML datafiles" Wiki entry is a blank page, and an XML input file only appears to be mentioned in one place, so there's a pretty good chance this can just be purged.

**Comment by eberleim** [comment]
Xerces library is now made optional in CMake (#1091), and will warn if a user attempts to load xml handler after self-building with no xerces present. Packaged versions will include Xerces in the bundle.
