### ISSUE TITLE
Investigate Github Actions and/or CPACK for release process

### ISSUE THREAD

**Issue by trevorhardy** [gridlab-d/gridlab-d#1371]
Develop release method for v5 release, ideally getting Github actions in place to get us started on CI/CD as a regular part of the development process.

**Comment by ftuffner** [comment]
@eberleim Note for documenting - when testing some of this on Friday, it looked like the shortcut/icon on Windows was being dumped to the "old path" for Windows and may have issues on newer versions of Windows.  We'll need to investigate/verify.
