### ISSUE TITLE
Update COPYRIGHT and LICENSE for build output

### ISSUE THREAD

**Issue by eberleim** [gridlab-d/gridlab-d#1373]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
the COPYRIGHT and LICENSE files are deeply out of date and should be updated.

-------------------------------------------------------------------------------------------------------------

**Comment by trevorhardy** [comment]
Updated.
