### ISSUE TITLE
Mac build error, 'isfinite'

### ISSUE THREAD

**Issue by trevorhardy** [gridlab-d/gridlab-d#1393]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Error while compiling GridLAB-D on my Mac.

macOS: 12.5.1
clang: 13.1.6 (clang-1316.0.21.2.5)
hardware: Mac M1 (ARM)
GridLAB-D: commit [e1a55d1](https://github.com/gridlab-d/gridlab-d/commit/e1a55d141219d99a6f1255b7c27e78cae2d18fdc) GridLAB-D develop branch the morning of Sept 9th.

## Please provide the exact error/warning/failure message printed on the console.
Many versions of the following:
```
[ 80%] Building CXX object powerflow/CMakeFiles/powerflow.dir/capacitor.cpp.o
/Users/vmuser/gridlab-d/gldcore/random.cpp:1029:8: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
                if (!finite(sample[i]))
                     ^~~~~~
                     isfinite
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/math.h:452:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
/Users/vmuser/gridlab-d/gldcore/random.cpp:1045:8: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
                if (!finite(sample[i]))
                     ^~~~~~
                     isfinite
```

-------------------------------------------------------------------------------------------------------------

**Comment by trevorhardy** [comment]
Retested with gcc 12 and getting similar results:

```
[ 96%] Building CXX object gldcore/CMakeFiles/gridlabd.dir/property.cpp.o
[ 96%] Building CXX object gldcore/CMakeFiles/gridlabd.dir/random.cpp.o
/Users/vmuser/gridlab-d/gldcore/random.cpp:878:8: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
                if (!finite(sample[i]))
                     ^~~~~~
                     isfinite
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/math.h:452:1: note: 'isfinite' declared here
isfinite(_A1 __lcpp_x) _NOEXCEPT
^
/Users/vmuser/gridlab-d/gldcore/random.cpp:896:8: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
                if (!finite(sample[i]))
                     ^~~~~~
                     isfinite
```

**Comment by eberleim** [comment]
the `finite` method is an old  was deprecated by Apple (and in general is not recommended) a few years ago, and still existed for MacOS 10, but as of 11 is now fully unsupported. I'm going to make a patch that replaces all uses of `finite` with the standard defined `isfinite` since that should be valid for all platforms now. 
@trevorhardy try pulling the `bugfix/1393` branch and see if that works on M1.

**Comment by trevorhardy** [comment]
Build succeeds; yeah! 

Bad news: all autotests fail with empty error logs. I did have to `sudo make install` to get "gridlabd.sh" to install (the OS threw a warning about not being able to install it when I just did `make install`). I am using "gridlabd.sh" to run the autotest so maybe related?

**Comment by trevorhardy** [comment]
I'm going to close this out and open another issue that is focussed on getting GridLAB-D to run on the M1.
