### ISSUE TITLE
Parent and Child Node Phase Mismatch on Delta-Connected Loads

### ISSUE THREAD

**Issue by temcdrm** [gridlab-d/gridlab-d#1411]
The following describes a line-to-line load between phases B and C, at a two-phase pole that has the N conductor present:
```
object node {
  name "646";
  phases BCN;
  nominal_voltage 2401.78;
}
object load {
  name "ld_646";
  parent "646";
  phases BCD;
  nominal_voltage 2401.78;
  base_power_B 265186.73; // adjusted for use with fractions and pfs
  current_fraction_B 1.000000;
  current_pf_B 0.867313;
}

```
**It used to solve** (correctly, I thought) **in version 4.3**, but now it fails with the message:
`ERROR    [INIT] : init_load(obj=66;ld_646): unhandled exception - NR: Parent and child node phases for nodes 646 and ld_646 do not match!
`
The corresponding autotest case has just the _load_ at _l646_, with phases BCD.  It also has phases BCN coming in from _l645_, so it's representing the same situation as above.  However, it constitutes a special adjustment. Furthermore, what would happen if the N conductor needed to run past _l646_ in the autotest case?  It would be coming from a load that has BCD phasing. 

The behavior should be the same as in version 4.3x.

**Comment by ftuffner** [comment]
@temcdrm - quick question - is this using just standard NR (and not the FPI approach)?  That might help track it down.

Quite possibly a bug introduced in the parent/child extension work, since that is the main thing that changed since v4.3.

**Comment by ftuffner** [comment]
@temcdrm Disregard - I see you already have a pull request, so we'll check that.

**Comment by ftuffner** [comment]
FYI, this is definitely a bug - this was a logic failure when I did the parent/child extension work, as alluded to in the earlier note.

**Comment by ftuffner** [comment]
@temcdrm Can you verify the code change works for you?  Your update worked, but the "theory" behind the original code was flawed and what caused the original issue.  I simplified it and move the "spirit" of the checks to load.cpp.
