### ISSUE TITLE
Issue while installing GRIDLAB-D using source code

### ISSUE THREAD

**Issue by anurag1806** [gridlab-d/gridlab-d#1473]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

While installing, I keep getting this error "autoreconf-2.72: error: automake failed with exit status: 1". Before this error I was also getting these errors.

1) configure.ac:255: error: required file 'powerflow/Makefile.in' not found
2) configure.ac:255: error: required file 'gridlabd.spec.in' not found
3) Makefile.am:6: error: required directory ./powerflow does not exist

## Please provide the steps to reproduce.

I can upload the github files but do not know how to upload them.

## If possible, please provide any screenshots and other supporting information.

![GRIDLAB_D issue_1](https://github.com/user-attachments/assets/0e97302a-c373-4b93-90a0-12dca3ff1d0e)

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
The scripts in the old_autobuild_scripts are deprecated and should not be used for compiling - there have been source code changes that make them incompatible.

Please use the instructions in the readme.md of located on [on ShoutWIki](https://gridlab-d.shoutwiki.com/wiki/CMake_Build) for building GridLAB-D, preferably from the release/5.2 (or v5.2 tag), develop, or master branches (basically in that order).
