### ISSUE TITLE
#159 Troubleshoot parser doesn't like macros,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#159]
The troubleshoot page parser does not like macro functions with other statements afterwards. e.g., overhead_line.cpp used to have:  

> if (config-&gt;phase##ph##_conductor &amp;&amp; \  
> 
> > !gl_object_isa(config-&gt;phase##ph##_conductor, \overhead_line_conductor)) \  
> 
> throw \invalid conductor for phase \ #ph \ of overhead line\; \  
> /\* TROUBLESHOOT The conductor specified for the indicated phase is not necessarily an overhead line conductor, it may be an underground or triplex-line only conductor */ \  
> 
> else if ((!config-&gt;phase##ph##_conductor) &amp;&amp; has_phase(PHASE_##ph)) \  
> 
> > throw \missing conductor for phase \ #ph \ of overhead line\;  
> > /\* TROUBLESHOOT  
> > The conductor specified for the indicated phase for the overhead line is missing  
> > or invalid.  
> > */  

as code to check the phases. When the troubleshoot parser came through, it found the first TROUBLESHOOT message, but then proceeded to include the else if and second TROUBLESHOOT as part of the actual troubleshooting message (for the first throw). This problem is no longer an issue in overhead_line.cpp (via functions), but still may pop up in the future.  

,

**Comment by jcfuller1** [comment]
Fixed with Troubleshoot updates in 2012.
