### ISSUE TITLE
#185 Indexing still doesn't like large values,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#184]
When sufficiently large ID numbers are used by the GLM loader for internal object reference, the correspondingly large lookup table cannot be used properly. The solution is to use a non-array data structure of some fashion to store the objects with their load-time ID number. Constructing arrays with hundreds of thousands elements for some two hundred objects is simply inefficient.  

,

**Comment by jcfuller1** [comment]
Doesn't appear to be an issue anymore.  Closing.
