### ISSUE TITLE
#361 Standardize tree for automake platform,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#361]
The current install tree is muddled and confusing. We need to simplify it so it basically works as follows for all automake platforms:  

$(prefix)/bin  

> gridlabd : shell script that includes all necessary environment settings  
> gridlabd.bin : executable binary  

$(prefix)/etc/gridlabd  

> ...all other files  

'gridlabd' is now 'gridlabd.bin'.  

'gridlabd.sh' is now 'gridlabd' and is what users usually run to start GridLAB-D.  

The libraries do not require versions, nor do they require a 'lib' prefix anymore.   

gridlabd.conf needs a MACOSX platform setup.  

The default install prefix is /usr.  

,

**Comment by eberleim** [comment]
autoconfig has been deprecated in v5.0 and replaced with CMake in #1091 which resolves these issues.
