### ISSUE TITLE
#454 Locking does not work in win32 when using runtime classes,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#454]
The currently installed version of mingw is too old to support hardware-based locking. The preferred solution is to install a newer version of mingw (i.e., 4.1 or better).  

An alternate solution is to allow rt/gridlabd.h to employ software locking instead of requiring hardware locking only.   

,

**Comment by ftuffner** [comment]
Win32 support long since deprecated.  Closing as part of ticket cleanup.
