### ISSUE TITLE
#619 superLU fails to notice a matrix is singular sometimes,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#619]
superLU occasionally iterates on a matrix that has obviously become singular. fault_check can be put into the system to supplement this check, but there may be options inside superLU to fix it.  

,

**Comment by ftuffner** [comment]
Islanding functionality going in as part of #730 migrations to 4.1 should help fix this.  Otherwise, closing this since most "special cases" get added as we discover them - a dedicated ticket is not needed.  superLU special flags were never uncovered to help with this.
