### ISSUE TITLE
#654 Remove deprecated test folders,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#654]
Old test folders (old unit testing) have a number of ad\ GLMs in them. Users are attempting to use these sample files without success. Need to remove those folder. However, the working tests should be saved and added to a central repository folder for future use.  

,

**Comment by RayJarry** [comment]
Working tests are saved in /models, other failed  tests are moved to an obsolete_tests folder. Old test folders are removed. Closing this ticket.
