### ISSUE TITLE
#655 Models folder may have old models,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#655]
\Models\ folder in the main folder has sample files. I believe these are the sample files that get downloaded with the executable. Some of these files are old and out-of-date and need to be upgraded over time.  

For future builds, this folder needs to be alidated\ as part of the build process, as in they need to at least load up and run successfully. Suggest using the new \job\ command in trunk to run it during the build process. If any of the files fail, then the build should be halted (or a message sent, whichever is easiest to implement).  

,

**Comment by jcfuller1** [comment]
This has been handled, in some form.  See #654 for the rest.
