### ISSUE TITLE
#659 Suggested Matlab link upgrades,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#659]
1) Add a alid_to\ ability to the model. Currently, it re-synchronizes with Matlab every time there is a new iteration or sync call...this can be a massive transfer of data that's not necessary and slows the simulation. Suggest a alid_to\ feature, maybe be making the Matlab link an \object\, that disconnects Matlab and GLD for a given amount of time.  

2) A list / grouping function would be handy, i.e., I want the cooling setpoint for every house on groupid feeder1. This will be helpful for global optimization scenarios.  

3) Convert the current GLM syntax to something more inline with other GLM syntax. Specifically, the Matlab link is looking for a single line of code up to 1024 characters long, without carriage returns. Suggest making it more flexible, maybe use object syntax {} to define start and finish of code.  

4) Currently debug or display options in the Matlab code do not get displayed, i.e., passed from the Matlab code out to the command line. Makes it very difficult to debug. I imagine this is a setting in activating the Matlab command window, but unsure.  

,

**Comment by afisher1** [comment]
Native MATLAB support is deprecated please use HELICS for interfacing with MATLAB and GridLAB-D. Closing.
