### ISSUE TITLE
#676 Add support for Xcode build,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#676]
Create an xcode&lt;N&gt; folder in SVN for xcode builds under the various versions of Xcode available  

,

**Comment by jcfuller1** [comment]
@trevorhardy  Do you still use XCODE with GLD?

**Comment by trevorhardy** [comment]
Rather than provide Xcode files, I've written a tutorial on using Xcode as an IDE for GridLAB-D.

http://gridlab-d.sourceforge.net/wiki/index.php/Mac_OSX/Xcode
