### ISSUE TITLE
#694 DMG welcome screen has outdated info,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#694]
It says \Version 2.0 was released in fall 2009.\ but should say \Version 2.3 was released spring 2013\  

,

**Comment by jcfuller1** [comment]
@nikhilgupta10 or @trevorhardy Can one of you guys verify this?

**Comment by trevorhardy** [comment]
I'll verify this.

**Comment by trevorhardy** [comment]
Welcome screen on 3.2 states release date was Fall 2015. I'm assuming this text will get updated for the next release.
