### ISSUE TITLE
#696 Update Market module,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#696]
The Market module is to have the direct pointers and function calls replaced with core callbacks, to adapt with the new conventions introduced with the 3.0 'trunk' API.  
The 'enhanced' version of the market module will replace all pointers and function calls to members with GL callbacks in both the 'auction' and 'controller' classes, while not changing any of the functionality, or the other classes within the module.  

,

**Comment by jcfuller1** [comment]
@afisher1 - Has been successfully converted for main functions (auction, controller, and passive_controller).
