### ISSUE TITLE
#725 Troubleshooting source link goes to the wrong repository,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#725]
Since the source code is no longer connected to TRAC, the troubleshooting link must now be changed to link to the SF code repo instead of the TRAC repo.  

,

**Comment by jcfuller1** [comment]
Please correct this as part of the migration to GitHub and ShoutWiki

**Comment by nikhilgupta10** [comment]
@ntenney would investigate this and re-link pointing between the new wiki (http://gridlab-d.shoutwiki.com/wiki/Main_Page) and Githhub repository.

**Comment by nikhilgupta10** [comment]
@ntenney what is the status of this issue?

**Comment by dchassin** [comment]
The latest update is jojoba version 3.2 in June 2015. Evidently it’s not working.

**Comment by ntenney** [comment]
The new locations for the troubleshooting and doxygen are:

https://www.gridlabd.org/troubleshooting/4.0/index.html
https://www.gridlabd.org/doxygen/4.0/index.html

**Comment by dchassin** [comment]
Note also that the code ref links in the troubleshooting docs are no longer correct either.

**Comment by ntenney** [comment]
Thanks. I'll look into that.

**Comment by afisher1** [comment]
The toubleshooting locations seem to be working. Closing
