### ISSUE TITLE
#736 Compilation errors with Linux,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#736]
Running utoreconf -isf\  

host$ autoreconf -isf  
configure.ac:235: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body  
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...  
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...  
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...  
m4/gld_get_nprocs.m4:2: GLD_GET_NPROCS is expanded from...  
configure.ac:235: the top level  
configure.ac:239: omit leading './' from config file names such as './Makefile';  
configure.ac:239: remake rules might be subtly broken otherwise  
core/Makefile.am:3: `pkglibdir' is not a legitimate directory for`PROGRAMS'  
core/Makefile.am:4: `pkglibdir' is not a legitimate directory for`SCRIPTS'  
core/Makefile.am:2: `pkglibdir' is not a legitimate directory for`DATA'  
core/Makefile.am:78: variable `EXTRA_gridlabd_bin_SOURCES' is defined but no program or  
core/Makefile.am:78: library has`EXTRA_gridlabd_bin' as canonical name (possible typo)  
core/Makefile.am:13: variable `gridlabd_bin_SOURCES' is defined but no program or  
core/Makefile.am:13: library has`gridlabd_bin' as canonical name (possible typo)  
core/rt/Makefile.am:1: `pkglibdir' is not a legitimate directory for`DATA'  
configure.ac:239: required file `commercial/Makefile.in' not found  
configure.ac:239: required file`optimize/Makefile.in' not found  
./Makefile.am:6: required directory ./commercial does not exist  
./Makefile.am:6: required directory ./optimize does not exist  

and so,   

host$ ./configure  
config.status: error: cannot find input file: `./Makefile.in'  
rm: cannot remove`core': Is a directory  

Thank you  

,

**Comment by afisher1** [comment]
This has been resolved
