### ISSUE TITLE
#74 Doxygen warnings need to be fixed,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#74]
Warning: ignoring unsupported tag `DOXYFILE_ENCODING      =' at line 26, file doxygen/gridlabd.conf
    Warning: ignoring unsupported tag`CPP_CLI_SUPPORT        =' at line 211, file doxygen/gridlabd.conf
    Warning: ignoring unsupported tag `INPUT_ENCODING         =' at line 480, file doxygen/gridlabd.conf
    Warning: ignoring unsupported tag`EXCLUDE_SYMBOLS        =' at line 522, file doxygen/gridlabd.conf
    Warning: ignoring unsupported tag `MSCGEN_PATH            =' at line 1119, file doxygen/gridlabd.conf
    Warning: ignoring unsupported tag`DOT_GRAPH_MAX_NODES    =' at line 1229, file doxygen/gridlabd.conf
    /var/www/html/gridlabd.pnl.gov/source/commercial/multizone.cpp(1): Warning: Unsupported xml/html tag <verbatim> found
    /var/www/html/gridlabd.pnl.gov/source/commercial/multizone.cpp(3): Warning: Unsupported xml/html tag </verbatim> found
    /var/www/html/gridlabd.pnl.gov/source/core/legal.c(88): Warning: explicit link request to 'SUCCESS' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/core/legal.c(88): Warning: explicit link request to 'FAILED' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/core/legal.c(70): Warning: explicit link request to 'SUCCESS' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/core/legal.c(70): Warning: explicit link request to 'FAILED' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/core/module.c(2): Warning: end of comment block while expecting command </em>
    /var/www/html/gridlabd.pnl.gov/source/climate/climate.h(78): Warning: The following parameters of tmy2_reader::header_info(char *city, char *state, int *degrees, int *minutes, int *long_deg, int *long_min) are not documented:
      parameter long_deg
      parameter long_min
    /var/www/html/gridlabd.pnl.gov/source/climate/climate.h(88): Warning: The following parameters of tmy2_reader::read_data(double *dnr, double *dhr, double *tdb, double *rh, int *month, int *day, int *hour, double *wind=0) are not documented:
      parameter rh
      parameter wind
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(15): Warning: explicit link request to 'require_voltage_control' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(16): Warning: explicit link request to 'type' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(18): Warning: explicit link request to 'to' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(18): Warning: explicit link request to 'flag' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(18): Warning: explicit link request to 'NF_HASSOURCE' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(21): Warning: explicit link request to 'SWING' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(23): Warning: explicit link request to 'PV' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/node.cpp(28): Warning: explicit link request to 'PQ' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/powerflow/powerflow.cpp(2): Warning: end of comment block while expecting command </em>
    /var/www/html/gridlabd.pnl.gov/source/powerflow/powerflow.cpp(4): Warning: found </em> tag without matching <em>
    /var/www/html/gridlabd.pnl.gov/source/java/GridlabD.java(9): Warning: explicit link request to 'DEFINE' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/java/GridlabD.java(9): Warning: explicit link request to 'DEFINE' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/java/GridlabD.java(9): Warning: explicit link request to 'DEFINE' could not be resolved
    /var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
    /var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
    /var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
    /var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(614): Warning: found </c> tag without matching <c>
    /var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
    /var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(614): Warning: found </c> tag without matching <c>

08/19/08 09:16:51 changed by mhauer ¶  
Down to wonky warnings, some unbalanced \em tags that I can't find, and warnings out of the odbc++ code, which is technically external.  

```
<unknown>(182476555): Warning: end of comment block while expecting command </em>
<unknown>(182549851): Warning: end of comment block while expecting command </em>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/powerflow/powerflow.cpp(6): Warning: found </em> tag without matching <em>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/tape_odbc/odbc++/types.h(614): Warning: found </c> tag without matching <c>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/home/buildbot/projects/Gridlab-D/slaves/linux-full/linux-full/build/core/odbc++/types.h(614): Warning: found </c> tag without matching <c>
```

08/22/08 12:46:20 changed by dchassin ¶  
Got it down to  

```
/var/www/html/gridlabd.pnl.gov/source/core/module.c(2): Warning: end of comment block while expecting command </em>
/var/www/html/gridlabd.pnl.gov/source/powerflow/powerflow.cpp(2): Warning: end of comment block while expecting command </em>
/var/www/html/gridlabd.pnl.gov/source/powerflow/powerflow.cpp(4): Warning: found </em> tag without matching <em>
/var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/var/www/html/gridlabd.pnl.gov/source/tape_odbc/odbc++/types.h(614): Warning: found </c> tag without matching <c>
/var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(615): Warning: end of comment block while expecting command </code>
/var/www/html/gridlabd.pnl.gov/source/core/odbc++/types.h(614): Warning: found </c> tag without matching <c>
```

,

**Comment by ftuffner** [comment]
Doxygen support basically neglected.  Closing as part of ticket cleanup
