### ISSUE TITLE
#757 Downloading versions of GLD,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#757]
We need to overhaul the download utton\ on Sourceforge. This should probably include:  

1) Ability to select between v2.3.1 and v3.0 (and eventually v3.1).  

2) Consider allowing folks to select their OS rather than auto-detecting. This has always seemed to be a little flaky, especially on Linux and OS. This will also give us the opportunity to say \we support OSx\ or \we support RHELx\, etc., and point folks to the build page if they want to use a different version or contact such and such if you would like to see such and such.  

3) Other suggestions?  

,

**Comment by jcfuller1** [comment]
No longer a valid issue with move to GitHub.
