### ISSUE TITLE
#762 Climate and real-time data,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#762]
Currently, the climate module _mostly_ supports real-time input of weather data in server modes. However, the solar calculations (breaking DN, Diffuse, and GH into solar flux directions) cannot be added directly.  

For real-time applications, this feature would be handy. Ideally, the user would be able to modify existing objects to feed in information. This would be similar to how CSV reader allows it to be fed from a tape player, accessing all of the TMY2 data variables that are available, then pushing derivative information out to the various objects.  

Please perform this work in ticket 716.  

,

**Comment by jcfuller1** [comment]
This has been completed.
