### ISSUE TITLE
#769 Build failures in v3.0,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#769]
A couple of components are still missing for proper Linux and Mac builds to release for public consumption:  

1) RPMs are still not being produced for Linux.  
2) Documentation of build procedure changes, particularly upgrade requirements for tools (automake, autoconf, sed, etc.).  
3) Documentation / location of old build tools for older OS's.  

,

**Comment by jcfuller1** [comment]
Done.
