### ISSUE TITLE
#771 Support for GKN-style underground cables with concentric neutral,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#771]
I'm trying to model an underground cable consisting of three conductors for the three phases and a concentric neutral around them.  
(see: http://www.nexans.ch/eservice/Switzerland-en/navigate_295244/Low_voltage_cables_type_GKN_Cu.html)  

As these types of cables are widely used in switzerland it would be great to see them supported within GridlabD  

,

**Comment by jcfuller1** [comment]
Addressed as part of changes to concentric neutrals - merging into v4.1
