### ISSUE TITLE
#791 Mac build fails,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#791]
Follow-up to [#739](739). Building on Snow Leopard (10.6.8) gives the following  

```
host% autoreconf -isf
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

No documentation is provided in the wiki docs about what should be done to remedy this problem. Recommend adding an item in the build instructions or build FAQ in the section about Mac builds.  

,

**Comment by jcfuller1** [comment]
This was addressed as part of conversion to MinGW.
