### ISSUE TITLE
#800 Prototypical feeders have voltage errors,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#800]
Most common is   

object meter:7053 {   

> name R3-12-47-3_meter_1;  
> phases ABCN;  
> voltage_A 7200+0.0j;  
> voltage_B -3600-6235j;  
> voltage_C -3600+6235j;  
> nominal_voltage 7200;   

}  

where the nominal voltage should be 480. This is a holdover from old modeling that is now explicitly caught in the error checks.  

,

**Comment by jcfuller1** [comment]
Done in v3.1.
