### ISSUE TITLE
#803 Single phase Regulators cannot converge with control modes in NR,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#803]
An issue was reported where the iteration limit was reached on a single-phase regulator performing output_voltage control. I confirmed this behavior was happening for NR only with control modes output_voltage, line drop compensation, and remote node. I will attach the file I used to confirm this behavior. Please not that this behavior is only happening in NR. Also, regardless of the solver used, maximum tap reached warnings show up for the phases not present on the regulator. Checking the code I saw that there are no phase checks for triggering tap changes for the previously mentioned control modes.  

,

**Comment by jcfuller1** [comment]
Frank - is this still an issue, or primarily user error?

**Comment by jcfuller1** [comment]
Pretty sure this is fixed.
