### ISSUE TITLE
#805 makefile does not play nicely with non-SVN setups,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#805]
The makefile has a section that generates a build.h based on the results of an svn info command. If the directory is not an SVN repository (or if SVN isn't even installed), the call fails and stops the build.  

There should be some check to see if there are SVN markup files present, and to see if SVN is installed, before trying to fetch the SVN repo information.  

,

**Comment by jcfuller1** [comment]
Not needed with conversion to Git
