### ISSUE TITLE
#806 'gridlabd --validate [module]' breaks the validator,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#806]
I wanted to validate the reliability module after a few changes. No big deal. \gridlabd --validate reliability. Every single test failed, reporting   

Processing /Users/mhauer/gld/gld30git/taxonomy_feeders/autotest/test_R3-12.47-1_NRERROR [INIT] : unable to load 'reliability.glm': No such file or directory  
ERROR [INIT] : /Users/mhauer/gld/gld30git/taxonomy_feeders/autotest/test_R3-12.47-1_NR.glm error unexpected, code 1 (bad command) in 0.2 seconds  

or something similar. The validate process was trying to run 
eliability.glm\ for every single test, instead of the autotest GLM that it found.  

This is a feature that worked in the Python script, and was pretty handy to avoid running every single autotest.  

At a minimum, --validate should keep the following input parameters from causing unexpected behavior. At best, it will look for the module and run only the autotests in that module, if the module exists.  

,

**Comment by jcfuller1** [comment]
Will not fix.  This can be done manually by navigating to the correct folder.
