### ISSUE TITLE
#822 Merge misc small fixes from ticket 697 to 3.1,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#822]
This ticket is to create a branch to merge a series of small fixes from ticket 697 (the Ausgrid / Grid Solutions 2.3 branch) to 3.1.  

These changes will be checked in individually and noted in this ticket but are considered too small to justify creating individual tickets for in each case.  

They may be merged down into 3.1 either individually or collectively.  

,

**Comment by afisher1** [comment]
there is no feature branch 697 so I'm assuming it's been merged already. closing.
