### ISSUE TITLE
#824 Lean Schedules,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#824]
Implementation of a new schedule system that uses a lot less memory than the old schedule system.  

,

**Comment by jeffdaily** [comment]
Food for thought.  Looking at current development branch for reference:
```
commit 119c15ba27a1a2ac5d8523f968f468d7f57a6b5c
Merge: 19ea477 895eee8
Author: afisher1 <andrew.fisher@pnnl.gov>
Date:   Mon Apr 10 08:50:27 2017 -0700

    Merge branch 'develop' of https://github.com/gridlab-d/gridlab-d into develop
```

In the gldcore parser, sizeof(SCHEDULE) = 14826208 bytes, just shy of 15MB.  That means for each "schedule" block in a GLM, it takes 15MB to hold it.  The GLM example I'm looking at currently features 24 schedule blocks for a total of 356MB.

Here's a copy of what's in the gldcore/schedule.h header currently:

```C
#define int64 long long
typedef int64 TIMESTAMP;
#define MAXBLOCKS 4
#define MAXVALUES 64

/** The SCHEDULE structure defines POSIX style schedules */
typedef struct s_schedule SCHEDULE;
struct s_schedule {
    /* the output value must be first for transform to stream */
    double value;                       /**< the current scheduled value */
#ifdef _DEBUG
    unsigned int magic1;    /* values between magic1 and magic2 should never change once compiled */
#endif
    char name[64];                      /**< the name of the schedule */
    char definition[65536];             /**< the definition string of the schedule */
    char blockname[MAXBLOCKS][64];      /**< the name of each block */
    unsigned char block;                /**< the last block used (4 max) */
    unsigned char index[14][366*24*60]; /**< the schedule index (enough room for all 14 annual calendars to 1 minute resolution) */
    unsigned char dtnext[14][366*24*60];/**< the time until the next schedule change (in minutes) */
    double data[MAXBLOCKS*MAXVALUES];   /**< the list of values used in each block */
    unsigned int weight[MAXBLOCKS*MAXVALUES];   /**< the weight (in minutes) associate with each value */
    double sum[MAXBLOCKS];              /**< the sum of values for each block -- used to normalize */
    double abs[MAXBLOCKS];              /**< the sum of the absolute values for each block -- used to normalize */
    unsigned int count[MAXBLOCKS];      /**< the number of values given in each block */
    unsigned int minutes[MAXBLOCKS];    /**< the total number of minutes associate with each block */
#ifdef _DEBUG
    unsigned int magic2;
    unsigned int checksum;
#endif
    TIMESTAMP next_t;                   /**< the time of the next schedule event */
    TIMESTAMP since;
    double duration;                    /**< the duration of the current scheduled value (in hours) */
    double fraction;                    /**< the fractional weight of the block of the current value (pu time) */
    int flags;                          /**< the schedule flags (see SN_*) */
    SCHEDULE *next; /* next schedule in list */
};

```
I have not looked at this to any greater depth, but I wonder what the low hanging fruit might be?  Currently, all attributes of the SCHEDULE struct are sized statically, e.g., MAXBLOCKS, MAXVALUES.  Though convenient, these "MAX" sizes might instead be sparse.  I haven't done any analysis about that yet, but perhaps using dynamic memory allocation would at least not over-allocate.

**Comment by jeffdaily** [comment]
The "index" and "dtnext" attributes account for ~7.4MB each, so combined that makes it easily 99% of the total memory consumed by schedules.  I haven't learned these attributes yet, but that's definitely what needs to be considered.  No easy fixes it seems.

**Comment by jcfuller1** [comment]
Yes, the schedules were always a brute force alternative to player files... we had no idea we would be using them as much as we do.

Couple thoughts:
1)  Do we need to load the whole schedule into memory?  Could we dynamically create, for example, the next week?  How the performance impacts significant?  If it does have an impact, maybe we can flag a "lean, but slow" schedule?

2)  Could we compress the schedules?  The 'duration' variable already figures out how long (in time) a block is.  Schedules are often made up of big blocks of the same data for a long time. Could the duration concept just be extended to use a simple compression algorithm?

**Comment by dchassin** [comment]
The biggest single thing we could do is limit the schedule to only the year(s) being simulated.  It's rare we simulate more than 1 year at a time, yet we always generate all 14 years. Right there we could knock it down to around 1 MB. It would also speed loads quite a bit.

**Comment by dchassin** [comment]
Another thing to consider is replace all static buffers with dynamically allocated memory.  This would reduce memory use by as much a 75% for single block schedules as well as remove the static size limits on blocks, names, etc.  One downside though: it also makes calculating the memory usage of a schedule more difficult.

**Comment by jcfuller1** [comment]
RE: only load 1 year... that might be the easiest.  I forgot we did all 14 years simultaneously.

**Comment by jeffdaily** [comment]
What I'm thinking of doing is making the SCHEDULE->index and SCHEDULE->dtnext attributes dynamically allocated to only hold as many calendars as will be used.  More specifically, there will be an array of 14 pointers for each just like it is now, but I will only allocate and compute a given calendar if it will be used.

So now I need to figure out how many calendars are needed.  I'm thinking of using the starttime and stoptime to figure this out.

I thought perhaps the calendar index always started at 0, so I isolated the code for the calendar index calculation to test the behavior.  For the following clock I got a calendar index of 8 for both starttime and stoptime.
```
clock {
     timezone PST+8PDT;
     starttime '2009-01-01 00:00:00';
     stoptime '2009-01-02 00:00:00';
}
```
For my proposed approach I will only allocate and compute calendars corresponding to the range starttime through stoptime, and if stoptime isn't defined it will default to 14 as usual.  So even if stoptime is large, there is still potential for memory saving.

Comments on this approach?

**Comment by jcfuller1** [comment]
Makes sense to me.

**Comment by dchassin** [comment]
If I remember how I did it the calendar number is based on the day of week of jan 1 and whether it's a leap year. To know which calendars are used you should only need to evaluate that. I think there's a function to resolve that number in schedule.c someplace. I'm about to board a plane but if you have trouble finding it I can find it after I land this evening.

**Comment by jeffdaily** [comment]
How is global_starttime determined?

I thought I could use the value of global_starttime and global_stoptime during schedule_new() to determine whether this was a special case of simulating a single year.  For my GLM with the following clock
```
clock {
     timezone PST+8PDT;
     starttime '2009-01-01 00:00:00';
     stoptime '2009-01-02 00:00:00';
}
```
during schedule_new(), the global_starttime is 1230796800 (calendar 8).  Then later, during a call to schedule_index() the global_starttime has a different value of 1230791400 (calendar 5).

Here's sample code for the conditional:
```C
...
        if (!local_datetime(global_starttime, &dt_starttime)) {
            throw_exception("schedule_new() unable to determine local starttime", global_starttime);
        }
        if (!local_datetime(global_stoptime, &dt_stoptime)) {
            throw_exception("schedule_new() unable to determine local stoptime", global_stoptime);
        }
        if (dt_starttime.year == dt_stoptime.year) {
            unsigned int cal = ((dt_starttime.weekday-dt_starttime.yearday+53*7)%7)*2 + ISLEAPYEAR(dt_starttime.year);
...
        }
```

**Comment by jeffdaily** [comment]
I'll answer my own question here.   I think schedule_skew is what is causing my confusion.  It's not enough to know the global_starttime and global_stoptime if the calendar boundaries can still get crossed.

**Comment by dchassin** [comment]
The tricky part is that stoptime may not be predetermined.  I would seriously consider generating the calendars on demand.  If you need a calendar and the index pointer is null, then you generate it.

**Comment by jeffdaily** [comment]
Lazy generation of the calendars was going to be my suggestion now that I've evaluated what I'm up against trying to do this during GLM parsing.  As an alternative, I was going to propose setting a maximum schedule_skew value, such as 1 day.

**Comment by dchassin** [comment]
Creating schedules that aren't completely compiled requires changing how schedule_compile and schedule_createproc are built. Basically, schedule_compile_block would have to be called only for calendars that are needed (which means this would have to passed in).  Then schedule_index, schedule_value, etc would have to call schedule_compile_block and the dtnext reconstruction code whenever they encounter a null index.  Remember the dtnext can span calendars, so it gets really tricky when it's pointing to a calendar that hasn't been loaded yet.

What's more, multithreading has to be suppressed (wherever it occurs) when done on-demand calendars are used because they must be blocking operations, whereas during the loader process, the are not necessarily blocking.

**Comment by jeffdaily** [comment]
"Remember the dtnext can span calendars..."

I wonder if I'm hitting that issue already.  I'm taking small steps with my implementation and running validate within the residential module as I make changes to the code.  The only change I made was:
```diff
+#define MAXCALENDARS 14
+#define MAXMINUTES (366*24*60)
@@ -62,8 +64,8 @@ struct s_schedule {
-       unsigned char index[14][366*24*60];     /**< the schedule index (enough room for all 14 annual calendars to 1 minute resolution) */
-       unsigned char dtnext[14][366*24*60];/**< the time until the next schedule change (in minutes) */
+       unsigned char *index[MAXCALENDARS];     /**< the schedule index (enough room for all 14 annual calendars to 1 minute resolution) */
+       unsigned char *dtnext[MAXCALENDARS];/**< the time until the next schedule change (in minutes) */
```
to get ready for making these attributes dynamically allocated.  Then, during schedule_new() I'm allocating those arrays.
```C
       for (cal=0; cal<MAXCALENDARS; cal++) {
               sch->index[cal] = malloc(sizeof(unsigned char)*MAXMINUTES);
               if (sch->index[cal]==NULL) return NULL;
               memset(sch->index[cal],0,sizeof(unsigned char)*MAXMINUTES);

               sch->dtnext[cal] = malloc(sizeof(unsigned char)*MAXMINUTES);
               if (sch->dtnext[cal]==NULL) return NULL;
               memset(sch->dtnext[cal],0,sizeof(unsigned char)*MAXMINUTES);
       }
```
Those changes alone cause many tests to start failing.  I'm wondering if there are assumptions elsewhere in the code that sch->index and sch->dtnext are contiguous across calendars.  Is this what you mean by your statement that dtnext can span calendars?

**Comment by jcfuller1** [comment]
Its the old [14] part of the array - 14 independent calendars cover all possible calendar arrangements.  dtnext constructed all 14 of those possible calendars (at one second intervals).  So, when the schedule needed a value, dtnext is a function of [which calendar, i.e., year][seconds since new year].  

>> Then schedule_index, schedule_value, etc would have to call schedule_compile_block and the dtnext reconstruction code whenever they encounter a null index<<

This is pretty straightforward when schedule skew is positive... but what about negative, especially when going over a new year boundary.  Do we only keep one year of schedule in memory at all times or re-allocate each time we need on and just increase the memory size?  Do we deconstruct "past" schedules, or just leave them until the end of the simulation?  Ugh.

>> As an alternative, I was going to propose setting a maximum schedule_skew value, such as 1 day. <<

I don't have a problem with that, although I might suggest one week (I've seen models with up to one day shift, but never more).

**Comment by jeffdaily** [comment]
During schedule_compile_block(), the sch->weight[MAXBLOCKS*MAXVALUES] and sch->minutes[MAXBLOCKS] arrays will aggregate values across all 14 calendars for a given block.  I'm worried that the functions schedule_normalize() and schedule_weight() will no longer be correct if I don't compute over all 14 calendars.  I wonder if I can 'go through the motions' -- iterate over all calendars such that weight and minutes calculate correctly -- but don't actually store the index value at that time.  Then later compute the index and dtnext arrays as needed.

**Comment by jeffdaily** [comment]
@dchassin You mentioned earlier 

> One downside though: it also makes calculating the memory usage of a schedule more difficult.

How important is it that a schedule's size be calculable?  We could add a function such as schedule_size(SCHEDULE*) if needed.

**Comment by dchassin** [comment]
I would say it’s not so important to users if it isn’t using a lot of memory. But given that the purpose of this effort is specifically to reduce memory usage, it seems like being able to determine how effective that solution is in kind of important.

**Comment by jeffdaily** [comment]
I thought I should mention that as I've been doing my testing, I haven't found autotests that cover the use of schedule properties "normal", "weighted", "absolute", or "interpolated".  I'm not familiar enough with the autotests so I might not have exhausted my search.

**Comment by afisher1** [comment]
More likely there aren't any tests for those.

Sent from my iPhone

On Apr 14, 2017, at 1:07 PM, Jeff Daily <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought I should mention that as I've been doing my testing, I haven't found autotests that cover the use of schedule properties "normal", "weighted", "absolute", or "interpolated". I'm not familiar enough with the autotests so I might not have exhausted my search.

**Comment by jeffdaily** [comment]
Feature branch is pushed and ready for testing.
https://github.com/gridlab-d/gridlab-d/tree/feature/824

Note that the state of the develop branch was not passing all validation tests at the time I created the feature branch.  To the best of my knowledge, no additional tests were failing at this time.

Summary of work:
Made schedule compilation code slightly more modular.  During schedule_new(), only calendars within one week +/- of global_starttime will be allocated.  schedule_compile() still iterates over all 14 calendars -- keeping all normalization code identical -- but only assigns index and dtnext values if the calendar is actually allocated.  During schedule_index() -- which calls SET_CALENDAR() -- it will check whether the calendar has been allocated.  If not, it allocates and "recompiles" the index and dtnext arrays for the given calendar.

No deallocation takes place.  Just lazy allocation.

I don't expect GLM parsing to go any faster (or slower) with the way the code is written since we would otherwise have to alter how the normalization code is written.  I do expect initial memory use to go from 15MB per schedule down to approximately 2.25MB per schedule.

Looking forward to more testing from others.

**Comment by dchassin** [comment]
Regarding the normalization options, it's quite possible there are no official tests of those.  I have used them in the past though and they seem to work. But I've never checked the results with a hand calc to be sure they're given the correct answers.  This would be a really good thing to do soon, especially now that we have a code change that could alter the results in both subtle and significant ways.

**Comment by dchassin** [comment]
I just ran the `--scheduletest` self-test on `develop` and it fails a number of tests.  That issue goes beyond the fixes proposed here, but I suggest we address these problems as part of this work while we have the opportunity.

I'm also adding what I think are some appropriate normalization tests to the `autotest` folder.

Test result for `gridlabd --scheduletest`
~~~~
GridLAB-D Version 4.0
Test results from run started Sun Apr 16 08:11:31 2017
Command line: "/usr/local/bin/gridlabd.bin --scheduletest"

BEGIN: schedule tests
Schedule empty {  } sync to 2000-01-01 00:00:00 UTC...
   test passed
Schedule halfday-binary { * 12-23 * * * } sync to 2001-02-03 01:30:00 UTC...
 ! expected next time 2001/02/03 12:00:00 but found 2001-02-03 03:30:00 UTC
Schedule halfday-binary { * 12-23 * * * } sync to 2002-03-05 13:45:00 UTC...
 ! expected next time 2002/03/06 00:00:00 but found 2002-03-05 15:30:00 UTC
Schedule halfday-bimodal { * 0-11 * * * 0.25; * 12-23 * * * 0.75; } sync to 2003-04-07 01:15:00 UTC...
 ! expected next time 2003/04/07 12:00:00 but found 2003-04-07 03:30:00 UTC
Schedule halfday-bimodal { * 0-11 * * * 0.25; * 12-23 * * * 0.75; } sync to 2004-05-09 00:00:00 UTC...
 ! expected next time 2004/05/09 12:00:00 but found 2004-05-09 03:30:00 UTC
Schedule halfday-bimodal { * 0-11 * * * 0.25; * 12-23 * * * 0.75; } sync to 2005-06-11 13:20:00 UTC...
 ! expected next time 2005/06/12 00:00:00 but found 2005-06-11 15:30:00 UTC
Schedule halfday-bimodal { * 0-11 * * * 0.25; * 12-23 * * * 0.75; } sync to 2006-07-13 12:00:00 UTC...
 ! expected next time 2006/07/14 00:00:00 but found 2006-07-13 15:30:00 UTC
Schedule halfday-bimodal { * 0-11 * * * 0.25; * 12-23 * * * 0.75; } sync to 2007-08-15 00:00:00 UTC...
 ! expected next time 2007/08/15 12:00:00 but found 2007-08-15 03:30:00 UTC
Schedule quarterday-normal { * 0-5 * * *; * 12-17 * * *; } sync to 2008-09-17 00:00:00 UTC...
 ! expected value 0.5 but found 1
 ! expected next time 2008/09/17 06:00:00 but found 2008-09-17 01:45:00 UTC
Schedule quarterday-normal { * 0-5 * * *; * 12-17 * * *; } sync to 2009-10-19 06:00:00 UTC...
 ! expected next time 2009/10/19 12:00:00 but found 2009-10-19 07:45:00 UTC
Schedule quarterday-normal { * 0-5 * * *; * 12-17 * * *; } sync to 2010-11-21 12:00:00 UTC...
 ! expected value 0.5 but found 1
 ! expected next time 2010/11/21 18:00:00 but found 2010-11-21 13:45:00 UTC
Schedule quarterday-normal { * 0-5 * * *; * 12-17 * * *; } sync to 2011-12-23 18:00:00 UTC...
 ! expected next time 2011/12/24 00:00:00 but found 2011-12-23 19:45:00 UTC
!!! 11 schedule tests failed, 13 errors found
END: schedule tests
~~~~

**Comment by trevorhardy** [comment]
Merged latest develop into feature branch, --validated successfully (aside from the crazily Mac-specific failure of "test_filter_second" and the "test_schedule_..." Dave mentions above), and pushed merged branch back up to repository. (This was all done with Apple's clang compiler).

**Comment by afisher1** [comment]
looks like I need to run the --scheduletest on the branch and on the develop branch and see how things are.

**Comment by afisher1** [comment]
fixed the the normalize functionality of the schedules. The way the schedule_nomalize function was being called was incorrect along with some other incorrect use of the local flags variable and the sch->flags. everything is passing so I'm merging this work into develop and closing ticket.
