### ISSUE TITLE
#841 Installer issues - not installing all libraries,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#841]
User (dchassin) reported that on a clean install (using the downloadable version of 3.0 64 bit), the installer did not install the pthread library. Also had issues with MinGW fail to install, but may be unrelated.  

Machine: Win7, AMD64, no software installed beyond base Windows, Matlab, and Labview  

,

**Comment by afisher1** [comment]
Cannot repeat issue. Closing issue.
