### ISSUE TITLE
#856 Additional Specifications for Solar Panels,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#856]
The solar panel model is currently specified as an area and system power output -- it would be beneficial to expand the capabilities to include other means of specification (e.g., area and efficiency).  Please work with doug dot danley-contractor at nreca dot coop to absorb standard specifications.

See OMF GitHub ticket 171.,

**Comment by trevorhardy** [comment]
[OMF issue is closed]( https://github.com/dpinney/omf/issues/259) so closing out the GridLAB-D issue.
