### ISSUE TITLE
#869 Init_max_defer can bail out before all objects complete initialization,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#869]
The default value is set to 64 but should actually be set during initialization to the maximum rank.  Otherwise, by default the system cannot successfully initialize a highly deferred deep rank structure.,

**Comment by jcfuller1** [comment]
@afisher1 - has this been resolved?

**Comment by afisher1** [comment]
Yes I do remember this getting fixed with #920. closing issue.
