### ISSUE TITLE
#876 SVN does not ignore build related files,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#876]
When compiling GridLAB-D from source a large number of build-related temp and output files are created. These files rightly don't belong in the SVN repository, but because they are not on the ignore list, they are included in the list of changes for `svn status` or related GUI views.

Can we add such temp files to the SVN ignore list to clean-up developer's svn workspace?

(On OSX) the biggest culprits are:
 .dep
 .dirstamp
both of which are created in nearly every directory.

Other seemingly easy to ignore:
 *.m4

There are many others, including the makefile plus configure, libtool, and gridlab executables created during the build process. 
  ,

**Comment by trevorhardy** [comment]
Closing as we are no longer using SVN.
