### ISSUE TITLE
#902 matlab include path not found in configure.ac (linux, ubuntu 14.04),


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#902]
The attached patch fixes an issue with configure.ac finding the matlab include path. The attached patch also appropriately sets MATLAB_LDPATH. This is marked as major, as compilation fails on Ubuntu 14.04 if matlab is discovered (as linker variable is not correctly specified). For this reason, there would be real benefit in applying this patch to the v3.0 branch as well.,

**Comment by afisher1** [comment]
This has been fixed. see linking with matlab section of the MinGW/Eclipse build instructions on the wiki.
