### ISSUE TITLE
#905 autoconf.ac update to better support mysql,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#905]
I have attached a diff file which incorporates some changes to autoconf to remove the dependency on hardcoded paths for finding MySQL. There is also attached a bugfixed version of the macro described at the URL below, which is to be included in the m4 directory. 
http://www.gnu.org/software/autoconf-archive/ax_check_mysql.html

This is marked as major, as gridlabd will not find MySQL if installed through a conventional package manager (and so thus would be in the /usr/ directory as opposed to /usr/local).
,

**Comment by eberleim** [comment]
autoconfig has been deprecated in v5.0 and replaced with CMake in #1091 which resolves these issues.
