### ISSUE TITLE
#907 interval < -1 causes recorder to hang,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#907]
Giving values for the interval < -1 causes the recorder to hang and gridlabd to go into an infinite sync() loop.  Recommend checking interval during init() and flagging this condition as an error.,

**Comment by dchassin** [comment]
A fix is available at https://github.com/dchassin/gridlabd/commit/8bab8c12dda2aad04c2fa9af06ce9df58becc3c6

**Comment by D3k205** [comment]
The commit that was done for issues #907  and #1297 was to the development branch.
