### ISSUE TITLE
#909 enable glxmatlab in release,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#909]
Not sure if we're ready for this, but here what has to be done to make the matlab link pass validation in Windows:

1) Add \MATLAB\ preprocessor options.
2) Add .../extern/include to include path.
3) Add path to MATLAB .../extern/lib/win64/microsoft folder in linker options.
4) Fix #setenv to in GLM files to use the correct path to MATLAB.
5) Make sure PATH in environment include folder that has matlab DLLs.

In theory, this is supposed to be automated by pre-build script, but I'm not sure it's work right and it's probably unnecessary now that MINGW is on track to be the release build system.
,

**Comment by afisher1** [comment]
Native MATLAB support is deprecated please use HELICS for interfacing with MATLAB and GridLAB-D. Closing.
