### ISSUE TITLE
#911 Line library functions don't have complete checks,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#911]
Silly mistake, but ugly to find.  When creating a triplex line, I accidentally attached a configuration for an overhead line (see line 178 of attached file).  This resulted in a completely silent failure.  Tracked it down to the triplex_line recalc() function where it tried to access the variables, but the memory location didn't exist.  Need to add error checking to make sure we have the right information in the library configuration.,

**Comment by afisher1** [comment]
has this been address or do I need to punt this to 4.1?

**Comment by ftuffner** [comment]
Added explicit checks for triplex_line_configuration.  Other link types appear to already have it, so just updated for "more specific" gl_object_isa calls.  Added autotests for the triplex_line_conductor test.
