### ISSUE TITLE
#913 Links with same to and from node are not detected,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#913]
Link objects don't check as to whether the 'to' and 'from' node are the same node.  Currently, it allows a link object to loop around on itself.  In NR, this shows up as a parallel line (albeit hard to find).  Not sure what it does in FBS.

Is this a bug or feature that we might need for something I can't think of?,

**Comment by afisher1** [comment]
has this been fixed?

**Comment by ftuffner** [comment]
Added in simple catch to detect and throw an error.  Added autotests to find it in the future too.
