### ISSUE TITLE
#914 MYSQL module build problems,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#914]
In Hatwai (Version 3.1) the MySQL module is not compiled in. You can build your own version but there are number of settings that you must manually make in the mysql project in VS2005 to enable the module.
1) Add HAVE_MYSQL to the Preprocessor Settings.
2) Add the path to your MySQL Connector C include to your Include Path.
3) Add libmysql.lib to your linker dependencies.
4) Add the path to your MySQL Connector C library folder to your Library Search Path.
5) Copy libmysql.dll to your GridLAB-D executable/library folder.
There is also a typo in configure.bat at line 190. And the mysql_vsprops call doesn't work at all.,

**Comment by afisher1** [comment]
We will need to see if this is possible for our linux builds.

**Comment by afisher1** [comment]
I can build the mysql library just fine. assuming fixed.
