### ISSUE TITLE
#916 voltdump crashes core when runtime classes are defined,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#916]
There is a missing set of tests in find.c for object searches that use module names, which are non-exitent for runtime classes.  As a result, the find_object functions fail catastrophically on bad pointers.  We need to add the following to find.c:

```
line 156: add !=NULL && b!=NULL &&\ before \strcmp\;
line 255: add \obj->oclass->module!=NULL &&\ before \compare_string\r
~~~~~,
```

**Comment by afisher1** [comment]
assumed fixed based off the comments
