### ISSUE TITLE
#917 mysql player error in timezone handling,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#917]
I am able to read from ~1000 tables as players in my model. One problem that I have is that the start time should be exactly the same as my start time of data that I have in mysql tables. 
data in all of these tables starts from 08-01-2013 00:00:00, my simulation can be run perfectly when I starts from 08-01-2013 00:00:00 or before this time. But when I change the start time in my simulation (for example 08-01-2013 01:00:00), it stops and I get this error:

```
ERROR [2013-08-01 01:00:00 EDT] : model commit failed
ERROR [2013-08-01 01:00:00 EDT] : exec halted: commit failure
FATAL [2013-08-01 01:00:00 EDT] : shutdown after simulation stopped prematurely
FATAL [2013-08-01 01:00:00 EDT] : environment startup failed: No such file or directory
```

Thanks,
Pedram,

**Comment by jcfuller1** [comment]
@afisher1 - please confirm as fixed.

**Comment by iut62elec** [comment]
This had been fixed in previous version and we tested it worked well!

**Comment by jcfuller1** [comment]
@iut62elec  -  Thank you sir!
