### ISSUE TITLE
#926 Update Statistics Order Incorrect,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#926]
The auction - controller sequence appears to have an ordering problem, particularly with the statistics calculation.

Currently:
- (PS) Auction clears
- (PS) Statistics update
- (S) Controller sets new setpoint (if it \won\ the bid)
- (S) Controller sets creates new bid

Whereas the statistics update should occur AFTER the controller sets its setpoint, so that the movement of the setpoint is using the statistics from the previous market cycle:
- (PS) Auction clears
- (S*) Controller sets new setpoint (if it \won\ the bid)
- (PS*) Statistics update
- (S) Controller sets creates new bid

Unfortunately, this is pretty deeply embedded and may take some effort to re-organize the order considering the order operations of auction-controller-load object.  Good news is that since most of the systems we do studies on are 5-minute markets over 24 hours (so 288 measurement points), the difference between two successive statistic calculations are relatively small.,

**Comment by afisher1** [comment]
This was moved into trunk before with ticket #877 which has been closed so I'm closing this issue.
