### ISSUE TITLE
#931 Convert WSU Restoration Code into GridLAB-D's Restoration Object,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#931]
This ticket will contain the work being done to convert the MATLAB restoration code that WSU has developed to a restoration object inside of GridLAB-D's powerflow module.,

**Comment by afisher1** [comment]
@ftuffner whats the status on this? Just want to know if we should move this to 4.1 or not?

**Comment by ftuffner** [comment]
Converted and implemented as part of earlier ticket 730 work on SourceForge, just never closed the ticket.  This code is implemented as the "restoration.cpp" inside powerflow, which was in r5240 (final) of SourceForge repository.  This functionality was pushed as part of 3.2.
