### ISSUE TITLE
#945 Fuses are not always operating properly in meshed topology mode,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#945]
Attached is a file from the forums that exhibits the behavior.  Switches had an issue with meshed topology that was fixed in 3.2.  It was though this was propogated to fuses as well, but that appears to have been missed.  The fix put in for 3.2 in switches may be needed for fuses as well.  There's a small possibility this is a duplication of ticket 808 (already faulted devices not being handled properly).  Further investigation is required.,

**Comment by afisher1** [comment]
Has this been looked into. Should I move this to 4.1?

**Comment by ftuffner** [comment]
Another example has been provided using a taxonomy feeder with fuses.  The fuse basically overrides any fault_check removals in its sync function, causing errors in the NR powerflow.  Looking into how to fix this.  Some fixes have been put together as part of #990, but they don't quite fix this issue either.

**Comment by ftuffner** [comment]
Fixed as part of f3a1c34979bffc64a005fd827add1d0572584c21.  Added in autotest to check for future breakage too.  Manually merging into 4.0 RC1, since it can pop up in reliability studies.
