### ISSUE TITLE
#962 Support Mac OS Line Endings,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#962]
This is a request to support Mac OS line endings. We ran into an issue where a player file was generated with Mac OS line endings and the glm ran successfully but the values played into by the player file were not correct. It appears what happened is that the player file read in until it filed the read line buffer and the value at the end of that line was the one that was played in to the glm for the entire simulaton. Changing the file to Unix line endings fixed the issue but we should really think about supporting Mac OS line endings.

Attaching the original files with Mac OS line endings for the player.,

**Comment by trevorhardy** [comment]
Confirmed this is still a problem with v4.3.

**Comment by trevorhardy** [comment]
Given that \CR line endings have not been native to Mac OS for two decades, we've decided that there is limited need to support them any longer. Any player files using these line endings can be converted to use modern line endings in tools such as [Notepad++](https://notepad-plus-plus.org), [BBedit](http://www.barebones.com/products/bbedit/index.html), or "dos2unix" on Ubuntu .
