### ISSUE TITLE
#965 Windows 10 autotest failures on trunk,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#965]
Any changes/trials/edits to this, please work in "bugfix/965" branch.

Three autotests fails during validation on Windows 10. The errors appear to be exit codes that are out of the expected range when exceptions are caught.

```
ERROR    [INIT] : c:\gridlabd\trunk\assert/autotest/test_complex_assert_imaginary_err.glm exception unexpected, code 127 (shell failed) in 6.9 seconds
ERROR    [INIT] : c:\gridlabd\trunk\assert/autotest/test_complex_assert_real_err.glm exception unexpected, code 127 (shell failed) in 5.5 seconds
ERROR    [INIT] : c:\gridlabd\trunk\assert/autotest/test_enum_assert_err.glm exception unexpected, code 127 (shell failed) in 6.4 seconds
~~~,
```

**Comment by nikhilgupta10** [comment]
Updated Windows 10 Fails. Some notes/updates while debugging this issue:
1. ../assert/autotest/test_complex_assert_angle_err.glm
Error when ran separately:  Assert failed on meter:0: Angle of voltage_A (0) not within 0.010000 of given value 0.174533 (doing what it is meant to. But why failing as an unexpected error?)

2. ../assert/autotest/test_complex_assert_real_err.glm
Error when ran separately:  Assert failed on meter:0: Magnitude of voltage_A (110) not within 1.000000 of given value 121 (doing what it is meant to. But why failing as an unexpected error?)

3. ../assert/autotest/test_enum_assert_err.glm
Error when ran separately: Assert failed on climate:0: interpolate=0 did not match 4.94066e-324 (doing what it is meant to. But why failing as an unexpected error?)

4. ../climate/autotest/test_cloud_tmy2.glm unhandled exception
Error when ran separately: Assert failed on DHHL_3_PV: Insolation 119.579 not within 0.010000 of given value 94.0257 (Something to do with the variable types? Why would this only fail in Windows 10? {or maybe only on my machine?})

5. ../climate/autotest/test_cloud_tmy3.glm unhandled exception
Error when ran separately: Assert failed on DHHL_3_PV: Insolation 126.438 not within 0.010000 of given value 105.791 (Something to do with the variable types? Why would this only fail in Windows 10? {or maybe only on my machine?})

6. ../generators/autotest/test_central_dg_control.glm
Error when ran separately: Assert failed on m1: imaginary part of measured_power_C +2415.13i not within 10.000000 of given value +34.857i (Something to do with the variable types? Why would this only fail in Windows 10? {or maybe only on my machine?})

7. ../generators/autotest/test_deltamode_diesel_dg_complex_err.glm
Error when ran separately:  Assert failed on BUS_1 - real part of voltage_A (8649.64) not within 0.020000 of given value 8654.57 (doing what it is meant to. But why failing as an unexpected error?)

8. ../gldcore/autotest/test_c_include.glm unhandled exception
Error when ran separately: C:\\Local Settings\Temp\gridlabd/noise.cpp:7:22: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>
                      ^
compilation terminated.
test_c_include.glm(15): load failed at or near 'class noise ...'

9. ../gldcore/autotest/test_double_array.glm unhandled exception
 Error when ran separately: c:\Users\gour967\Documents\SourceTree\GridLAB-D_Github\gridlab-d\gldcore\autotest\test_double_array
./test.cpp:7:22: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>
                      ^
compilation terminated.
test_double_array.glm(37): load failed at or near 'class test {...'

10. ../gldcore/autotest/test_external_null_source.glm unhandled exception
Error when ran separately: C:\\Local Settings\Temp\gridlabd/noise.cpp:7:22: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>
                      ^
compilation terminated.
test_external_null_source.glm(47): load failed at or near 'class noise ...'

11. ../gldcore/autotest/test_stream_out.glm unhandled exception
Error when ran separately: C:\\Local Settings\Temp\gridlabd/test.cpp:7:22: fatal error: gridlabd.h: No such file or directory
 #include <gridlabd.h>
                      ^
compilation terminated.
test_stream_out.glm(18): load failed at or near 'class test {...'

12. ../powerflow/autotest/test_duplicate_NR_err.glm
Error when ran separately:  NR: duplicate admittance entry found - check for parallel circuits between common nodes! (doing what it is meant to. But why failing as an unexpected error?)

**Comment by dchassin** [comment]
This seems to support the notion that the problem has to do with exit codes are not in the expected range.  Perhaps in Windows 10, the exit codes have a different data type.  Most of these should be return error codes (0<code<127) but instead are returning exception code (code>=255). The codes are supposed to conform to the XC_* values in gldcore/globals.h.  If would be useful to determine what value is being collected by the validate routine when it returns a non-zero error.

**Comment by afisher1** [comment]
This is confirmed fixed. @nikhilgupta10 should add some notes on what he had to do to get the validation script to pass 100%.

**Comment by nikhilgupta10** [comment]
All the above failures except the ones in the "description" of this issue were fixed by setting CXXFLAGS:
CXXFLAGS=-I../share/gridlabd

Did fresh GLD builds on multiple VMs with Windows 10 - They passed with 100% validate.
