### ISSUE TITLE
#976 Solar Azimuth indeterminant,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#976]
The solar_azimuth value calculated in SolarAngles::azimuth in solar_angles.cpp is giving indeterminant values from March(03/23) through September(09/20) around 23:00, 00:00 hours.Scenarios have been tested with years 2000,2001,2004,2008,2010 with tmy2 and tmy3 data input, time zones GMT,PST and the errors are consistant.,

**Comment by priyatm62** [comment]
The fix made earlier on solar zenith calculation has fixed this issue as well. The NaN values were due to acos() being performed on a value outside the bounds -1 to 1.
