### ISSUE TITLE
#996 - Phase checks sometimes fail for "backwards" radial lines

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#996]
The phase checks inside the initial NR routines sometimes fail indicating "too many phases are leaving a node" due to a bug in how the phase checks are performed.  This is especially apparent for strictly radial systems (e.g., 13-node system attached).  The phase checks need to be adjusted/rewritten to properly handle this scenario.

GLM attached later.

**Comment by ftuffner** [comment]
<script src="https://gist.github.com/ftuffner/245c688654a87b53b60fb80923ade040.js"></script>

**Comment by ftuffner** [comment]
https://gist.github.com/ftuffner/245c688654a87b53b60fb80923ade040

**Comment by ftuffner** [comment]
[test_IEEE_13_NR_revs.zip](https://github.com/gridlab-d/gridlab-d/files/638064/test_IEEE_13_NR_revs.zip)

**Comment by afisher1** [comment]
Has this been fixed?

**Comment by ftuffner** [comment]
Not sure which revision it got fixed in (may be pre-Git merge in 730 or similar), but the autotest with reversed lines seems to be in /develop and working.  Closing.
