### ISSUE TITLE
NR provides incorrect power in triplex system, FBS does fine

### ISSUE THREAD

**Issue by trevorhardy** [gridlab-d/gridlab-d#998]
In the attached model (and supporting files),  meter tpm2_R2-12-47-2_tm_38 has three child meters: 
  house_meter2_R2-12-47-2_tm_38
  solar_meter_house2_R2-12-47-2_tm_38
  battery_meter_house2_R2-12-47-2_tm_38

The sum of the powers in these three meters should be the value measured in tpm2_R2-12-47-2_tm_38.

This is the case when using FBS but not when using NR. Since Frank is the powerflow man, I'm going take the bold step and assign it to him out of the gate. Merry Christmas!

[triplex_NR_fail_FBS_solve.zip](https://github.com/gridlab-d/gridlab-d/files/642829/triplex_NR_fail_FBS_solve.zip)

**Comment by trevorhardy** [comment]
Re-adding model with voltage player files this time.
[triplex_NR_fails_FBS_solves.glm.zip](https://github.com/gridlab-d/gridlab-d/files/642848/triplex_NR_fails_FBS_solves.glm.zip)

**Comment by ftuffner** [comment]
Greatly simplified down to where a single house causes it.  Only appears to happen when a triplex_meter is parented to another triplex_meter, and the lower one has a house.  It doesn't appear to affect the underlying powerflow solution, just the current accumulation.

**Comment by ftuffner** [comment]
Fixed and closed ticket 998.  Was related to the "rotating current" value associated with houses being double-posted.  Basically, it would get accumulated into the child current injection, the accumulated a second time in the parent current injection.  Added the code to fix this.  The powerflow solution itself was unaffected.
